import {beforeEach,it,expect,vi} from "vitest";
vi.mock("server-only",()=>({}));
vi.mock("../../../../nostr/calendar-records",()=>({loadCalendarWalks:vi.fn()}));
vi.mock("../../../../lib/server-relay-config",()=>({serverReadRelays:vi.fn(()=>["wss://relay.example"])}));
vi.mock("../../../../server/share-image",()=>({managedBackground:vi.fn(),bundledCityBackground:vi.fn(),ensureShareImage:vi.fn()}));
vi.mock("../../../../server/share-preview",()=>({shareOrigin:vi.fn(()=>"https://app-staging.bitcoinwalk.org")}));
vi.mock("../../../../domain/media-request",()=>({parseMediaRequest:vi.fn()}));
vi.mock("../../../../nostr/authority",()=>({isSuperAdmin:vi.fn()}));
vi.mock("../../../../server/sponsor-logo-store",()=>({listSponsorLogoUploads:vi.fn(),previewSponsorLogo:vi.fn()}));
import {parseMediaRequest} from "../../../../domain/media-request";
import {isSuperAdmin} from "../../../../nostr/authority";
import {listSponsorLogoUploads,previewSponsorLogo} from "../../../../server/sponsor-logo-store";
import {loadCalendarWalks} from "../../../../nostr/calendar-records";
import {ensureShareImage,managedBackground} from "../../../../server/share-image";
import {POST} from "./route";
const request=(body=JSON.stringify({event:{pubkey:"a".repeat(64)}}))=>new Request("https://example.com/api/sponsors/assets",{method:"POST",body});
beforeEach(()=>{vi.resetAllMocks();vi.mocked(parseMediaRequest).mockReturnValue({action:"list-sponsor-assets"});});
it("denies non-admin inventory access",async()=>{expect((await POST(request())).status).toBe(403);expect(listSponsorLogoUploads).not.toHaveBeenCalled();});
it("denies invalid signatures",async()=>{vi.mocked(isSuperAdmin).mockReturnValue(true);vi.mocked(parseMediaRequest).mockReturnValue(null);expect((await POST(request())).status).toBe(403);});
it("returns no-store inventory to signed admin",async()=>{vi.mocked(isSuperAdmin).mockReturnValue(true);vi.mocked(listSponsorLogoUploads).mockResolvedValue([]);const response=await POST(request());expect(response.status).toBe(200);expect(response.headers.get("cache-control")).toBe("no-store");expect(await response.json()).toEqual({assets:[]});});
it("previews only the signed asset hash",async()=>{vi.mocked(isSuperAdmin).mockReturnValue(true);const command={action:"preview-sponsor-asset" as const,cityId:"00000000-0000-4000-8000-000000000001",sponsorPubkey:"a".repeat(64),hash:"b".repeat(64)};vi.mocked(parseMediaRequest).mockReturnValue(command);vi.mocked(previewSponsorLogo).mockResolvedValue({hash:command.hash,base64:"cG5n"});expect((await POST(request())).status).toBe(200);expect(previewSponsorLogo).toHaveBeenCalledWith(command);});
it("creates a content-addressed composite from an approved city and exact sponsor asset",async()=>{vi.mocked(isSuperAdmin).mockReturnValue(true);const command={action:"generate-sponsor-composite" as const,targetCityId:"00000000-0000-4000-8000-000000000001",sourceCityId:"00000000-0000-4000-8000-000000000002",sponsorPubkey:"a".repeat(64),hash:"b".repeat(64)};vi.mocked(parseMediaRequest).mockReturnValue(command);vi.mocked(loadCalendarWalks).mockResolvedValue([{revision:{city:{cityId:command.targetCityId,slug:"city",heroImageUrl:"https://example.com/city.webp"}},approval:{approval:{}}}] as never);vi.mocked(previewSponsorLogo).mockResolvedValue({hash:command.hash,base64:Buffer.from("logo").toString("base64")});vi.mocked(managedBackground).mockResolvedValue(Buffer.from("background"));vi.mocked(ensureShareImage).mockResolvedValue("c".repeat(64));const response=await POST(request());expect(response.status).toBe(200);expect(await response.json()).toEqual({url:`https://app-staging.bitcoinwalk.org/api/og/files/${"c".repeat(64)}.jpg`,hash:"c".repeat(64)});expect(ensureShareImage).toHaveBeenCalledWith(Buffer.from("background"),Buffer.from("logo"),undefined,"attention");});
it("rejects oversized request bodies",async()=>{expect((await POST(request("x".repeat(16385)))).status).toBe(413);expect(parseMediaRequest).not.toHaveBeenCalled();});
it("rejects unrelated signed commands",async()=>{vi.mocked(isSuperAdmin).mockReturnValue(true);vi.mocked(parseMediaRequest).mockReturnValue({action:"list-media-alerts"});expect((await POST(request())).status).toBe(403);});
