import {afterEach,describe,it,expect,vi} from "vitest";
import {fetchCitySuggestions,narrowCitySuggestions} from "./city-autocomplete";
import type {CitySearchResult} from "./geocode";
afterEach(()=>vi.useRealTimers());
describe("autocomplete request lifecycle",()=>{
 it("narrows existing suggestions immediately with each new letter and caps five rows",()=>{const rows=["Szczecin","Szczawnica","Szczyrk","Szczecinek","Szczytno","Szczucin"].map(cityName=>({cityName,name:cityName,latitude:0,longitude:0}));expect(narrowCitySuggestions(rows,"Szcz","Szcz")).toHaveLength(5);expect(narrowCitySuggestions(rows,"Szcze","Szcz").map(r=>r.cityName)).toEqual(["Szczecin","Szczecinek"]);expect(narrowCitySuggestions(rows,"Szczeci","Szcz")).toHaveLength(2);expect(narrowCitySuggestions(rows,"SzczecinX","Szcz")).toEqual([]);});
 it("retains provider language aliases once the current query returns",()=>{const rows=[{cityName:"Warsaw"}] as CitySearchResult[];expect(narrowCitySuggestions(rows,"Warszawa","Warszawa")).toEqual(rows);expect(narrowCitySuggestions(rows,"W","Warszawa")).toEqual([]);});
 it("returns suggestions through the same-origin proxy",async()=>{const f=vi.fn(async()=>Response.json({results:[{cityName:"Łódź"}]})),controller=new AbortController();expect(await fetchCitySuggestions("Łódź",controller.signal,f)).toEqual([{cityName:"Łódź"}]);expect(f).toHaveBeenCalledWith("/api/geocode?q=%C5%81%C3%B3d%C5%BA",{signal:controller.signal});});
 it("retries a rate-limited request once after two seconds",async()=>{vi.useFakeTimers();const f=vi.fn().mockResolvedValueOnce(new Response("",{status:429})).mockResolvedValueOnce(Response.json({results:[]}));const result=fetchCitySuggestions("City",new AbortController().signal,f);await vi.advanceTimersByTimeAsync(2000);expect(await result).toEqual([]);expect(f).toHaveBeenCalledTimes(2);});
 it("cancels a stale query while waiting to retry",async()=>{vi.useFakeTimers();const f=vi.fn(async()=>new Response("",{status:429})),controller=new AbortController(),result=fetchCitySuggestions("City",controller.signal,f);const assertion=expect(result).rejects.toThrow("Aborted");await vi.advanceTimersByTimeAsync(1);controller.abort();await assertion;await vi.advanceTimersByTimeAsync(3000);expect(f).toHaveBeenCalledTimes(1);});
 it("does not send already cancelled requests",async()=>{const controller=new AbortController();controller.abort();const f=vi.fn();await expect(fetchCitySuggestions("City",controller.signal,f)).rejects.toThrow();expect(f).not.toHaveBeenCalled();});
 it("shows failure after the bounded retry",async()=>{vi.useFakeTimers();const f=vi.fn(async()=>Response.json({error:"Busy"},{status:429})),result=fetchCitySuggestions("City",new AbortController().signal,f),assertion=expect(result).rejects.toThrow("Busy");await vi.advanceTimersByTimeAsync(2000);await assertion;expect(f).toHaveBeenCalledTimes(2);});
});
