import "server-only";
import {createHash,randomUUID} from "node:crypto";
import {lookup} from "node:dns/promises";
import {mkdir,readFile,rename,stat,writeFile} from "node:fs/promises";
import {isIP} from "node:net";
import {request as httpsRequest} from "node:https";
import {join} from "node:path";
import sharp from "sharp";
const MAX_BYTES=10*1024*1024,MAX_PIXELS=40_000_000;
const root=()=>process.env.BITCOINWALK_MEDIA_ROOT||join(process.env.TMPDIR||"/tmp","bitcoinwalk-media");
const files=()=>join(root(),"files"),manifestPath=()=>join(root(),"manifest.json");
export type MediaStatus="healthy"|"failed"|"missing"|"corrupt";
export type MediaRecord={id:string;cityId:string;actor:string;sourceUrl:string;internalUrl?:string;contentHash?:string;bytes?:number;storedAt:string;checkedAt:string;status:MediaStatus;error?:string};
type Manifest={version:1;records:MediaRecord[]};let mutation=Promise.resolve(),active=0;
async function manifest():Promise<Manifest>{try{const parsed=JSON.parse(await readFile(manifestPath(),"utf8"));return parsed.version===1&&Array.isArray(parsed.records)?parsed:{version:1,records:[]};}catch{return {version:1,records:[]};}}
async function save(value:Manifest){await mkdir(root(),{recursive:true,mode:0o700});const temp=manifestPath()+".tmp";await writeFile(temp,JSON.stringify(value,null,2),{mode:0o600});await rename(temp,manifestPath());}
async function mutate<T>(fn:(value:Manifest)=>Promise<T>):Promise<T>{let result!:T,error:unknown;mutation=mutation.then(async()=>{const value=await manifest();try{result=await fn(value);}catch(e){error=e;}await save(value);});await mutation;if(error)throw error;return result;}
const shownSource=(value:string)=>{const url=new URL(value);url.username="";url.password="";url.search="";url.hash="";return url.href;};
function publicAddress(address:string):boolean{if(isIP(address)===4){const p=address.split(".").map(Number),a=p[0],b=p[1];return !(a===0||a===10||a===127||a>=224||a===169&&b===254||a===172&&b>=16&&b<=31||a===192&&(b===0||b===168)||a===100&&b>=64&&b<=127||a===198&&(b===18||b===19)||a===192&&b===0&&p[2]===2||a===198&&b===51&&p[2]===100||a===203&&b===0&&p[2]===113);}const lower=address.toLowerCase();return isIP(address)===6&&!lower.startsWith("::")&&!lower.startsWith("fc")&&!lower.startsWith("fd")&&!/^fe[89ab]/.test(lower)&&!lower.startsWith("ff")&&!lower.startsWith("2001:db8");}
async function approvedAddress(hostname:string){const addresses=await lookup(hostname,{all:true,verbatim:true});if(!addresses.length||addresses.some(item=>!publicAddress(item.address)))throw new Error("The image host resolves to a private or reserved network address.");return addresses[0].address;}
async function download(value:string,redirects=0):Promise<Buffer>{const url=new URL(value);if(url.protocol!=="https:"||url.username||url.password)throw new Error("Use a public HTTPS image URL without embedded credentials.");if(redirects>3)throw new Error("The image URL redirected too many times.");const address=await approvedAddress(url.hostname);return new Promise((resolve,reject)=>{const req=httpsRequest({hostname:address,port:url.port||443,path:url.pathname+url.search,method:"GET",servername:url.hostname,headers:{Host:url.host,"User-Agent":"BitcoinWalk-Media/1.0",Accept:"image/png,image/jpeg,image/webp"},timeout:8000},res=>{const status=res.statusCode||0,location=res.headers.location;if(status>=300&&status<400&&location){res.resume();void download(new URL(location,url).href,redirects+1).then(resolve,reject);return;}if(status!==200){res.resume();reject(new Error(`Image server returned HTTP ${status}.`));return;}const type=String(res.headers["content-type"]||"").split(";",1)[0].toLowerCase();if(!["image/png","image/jpeg","image/webp"].includes(type)){res.resume();reject(new Error("The URL did not return PNG, JPEG or WebP content."));return;}const chunks:Buffer[]=[],declared=Number(res.headers["content-length"]||0);let done=false,total=0;const fail=(error:Error)=>{if(done)return;done=true;res.destroy();reject(error);};if(declared>MAX_BYTES){fail(new Error("The source image exceeds the 10 MB limit."));return;}res.on("data",chunk=>{total+=chunk.length;if(total>MAX_BYTES)fail(new Error("The source image exceeds the 10 MB limit."));else chunks.push(chunk);});res.on("end",()=>{if(!done){done=true;resolve(Buffer.concat(chunks));}});res.on("error",fail);});req.on("timeout",()=>req.destroy(new Error("The image download timed out.")));req.on("error",reject);req.end();});}
export async function importCityImage(input:{cityId:string;actor:string;sourceUrl:string;origin:string}){if(active>=2)throw new Error("Image processing is busy. Try again shortly.");active++;const visible=shownSource(input.sourceUrl),now=new Date().toISOString();try{return await mutate(async value=>{const hourAgo=Date.now()-3600_000,recent=value.records.filter(record=>Date.parse(record.storedAt)>hourAgo);if(recent.filter(record=>record.actor===input.actor).length>=10)throw new Error("Image import limit reached for this identity. Try again in one hour.");if(recent.length>=30)throw new Error("Global image import limit reached. Try again in one hour.");const cached=[...value.records].reverse().find(record=>record.cityId===input.cityId&&record.sourceUrl===visible&&record.status==="healthy"&&record.internalUrl);if(cached)return cached;try{const downloaded=await download(input.sourceUrl);const source=sharp(downloaded,{limitInputPixels:MAX_PIXELS,failOn:"warning"});const metadata=await source.metadata();if(!["jpeg","png","webp"].includes(metadata.format||"")||!metadata.width||!metadata.height)throw new Error("The downloaded file is not a supported decodable image.");const output=await source.rotate().resize(1536,1024,{fit:"cover",position:"attention"}).webp({quality:82,effort:5}).toBuffer();const hash=createHash("sha256").update(output).digest("hex");await mkdir(files(),{recursive:true,mode:0o700});const path=join(files(),hash+".webp");try{await stat(path);}catch{await writeFile(path,output,{mode:0o600});}const record:MediaRecord={id:randomUUID(),cityId:input.cityId,actor:input.actor,sourceUrl:visible,internalUrl:`${input.origin}/api/media/files/${hash}.webp`,contentHash:hash,bytes:output.length,storedAt:now,checkedAt:now,status:"healthy"};value.records.push(record);return record;}catch(error){value.records.push({id:randomUUID(),cityId:input.cityId,actor:input.actor,sourceUrl:visible,storedAt:now,checkedAt:now,status:"failed",error:error instanceof Error?error.message:"Image import failed."});throw error;}});}finally{active--;}}
export async function assertGenerationBudget(actor:string){const value=await manifest(),dayAgo=Date.now()-86_400_000,recent=value.records.filter(record=>record.sourceUrl.startsWith("generated:")&&Date.parse(record.storedAt)>dayAgo),dailyLimit=Math.max(1,Number(process.env.BITCOINWALK_IMAGE_DAILY_LIMIT||10));if(recent.length>=dailyLimit)throw new Error("Daily image-generation limit reached. Try again after the budget window resets.");if(recent.filter(record=>record.actor===actor).length>=5)throw new Error("Image-generation limit reached for this identity. Try again tomorrow.");}
export async function storeGeneratedCityImage(input:{cityId:string;actor:string;bytes:Buffer;model:string;origin:string}){if(active>=2)throw new Error("Image processing is busy. Try again shortly.");active++;const now=new Date().toISOString(),sourceUrl=`generated:${input.model}`;try{return await mutate(async value=>{await assertGenerationBudget(input.actor);try{const source=sharp(input.bytes,{limitInputPixels:MAX_PIXELS,failOn:"warning"}),metadata=await source.metadata();if(!["jpeg","png","webp"].includes(metadata.format||"")||!metadata.width||!metadata.height)throw new Error("The provider returned an unsupported image.");const output=await source.rotate().resize(1536,1024,{fit:"cover",position:"attention"}).webp({quality:82,effort:5}).toBuffer(),hash=createHash("sha256").update(output).digest("hex");await mkdir(files(),{recursive:true,mode:0o700});const path=join(files(),hash+".webp");try{await stat(path);}catch{await writeFile(path,output,{mode:0o600});}const record:MediaRecord={id:randomUUID(),cityId:input.cityId,actor:input.actor,sourceUrl,internalUrl:`${input.origin}/api/media/files/${hash}.webp`,contentHash:hash,bytes:output.length,storedAt:now,checkedAt:now,status:"healthy"};value.records.push(record);return record;}catch(error){value.records.push({id:randomUUID(),cityId:input.cityId,actor:input.actor,sourceUrl,storedAt:now,checkedAt:now,status:"failed",error:error instanceof Error?error.message:"Generated image could not be stored."});throw error;}});}finally{active--;}}
export async function auditMedia():Promise<MediaRecord[]>{return mutate(async value=>{for(const record of value.records){if(!record.contentHash||!record.internalUrl)continue;record.checkedAt=new Date().toISOString();try{const body=await readFile(join(files(),record.contentHash+".webp"));record.status=createHash("sha256").update(body).digest("hex")===record.contentHash?"healthy":"corrupt";record.error=record.status==="healthy"?undefined:"Stored image hash does not match its record.";}catch{record.status="missing";record.error="Stored image file is missing.";}}return value.records.filter(record=>record.status!=="healthy").sort((a,b)=>b.storedAt.localeCompare(a.storedAt));});}
export async function readMedia(hash:string):Promise<Buffer|null>{if(!/^[0-9a-f]{64}$/.test(hash))return null;try{return await readFile(join(files(),hash+".webp"));}catch{return null;}}
