import {DatabaseSync} from "node:sqlite";
import {afterEach,describe,expect,it,vi} from "vitest";
import {createCityActivation} from "../rustress/activation-contract";
import type {ProvisionConfig} from "../rustress/contract";
import {managedLnurl,managedNip05} from "./rustress-public-gateway";
const dbs:DatabaseSync[]=[];afterEach(()=>{dbs.forEach(db=>db.close());dbs.length=0;});
const reserved:ProvisionConfig={cityId:"00000000-0000-4000-8000-000000000001",version:1,domain:"bitcoinwalk.org",localPart:"madeira",brandPubkey:"a".repeat(64),authorityEventId:"b".repeat(64),approvalEventId:"c".repeat(64),brandEventId:"d".repeat(64),payoutVersion:1,payoutDestination:"organizer@example.org",walletRef:"bitcoinwalk-rustress",organizerBasisPoints:7900,retainedBasisPoints:2100,invoiceIssuance:"disabled"},active=createCityActivation(reserved);
function fixture(phase="verifying") {const db=new DatabaseSync(":memory:");dbs.push(db);db.exec("CREATE TABLE rustress_activation_task(activation_config TEXT,phase TEXT)");db.prepare("INSERT INTO rustress_activation_task VALUES(?,?)").run(JSON.stringify(active),phase);
  const transport=vi.fn<typeof fetch>(async url=>new Response(String(url).includes("nostr.json")?JSON.stringify({names:{madeira:active.brandPubkey}}):JSON.stringify({tag:"payRequest",callback:"https://bitcoinwalk.org/lnurlp/madeira/callback",metadata:"[]",minSendable:1000,maxSendable:100000}),{headers:{"Content-Type":"application/json"}}));
  return {db,transport,deps:{db,transport,origin:"http://127.0.0.1:18895"}};}
describe("managed public city gateway",()=>{
  it("serves only an applied activation and revalidates exact NIP-05 identity",async()=>{const f=fixture();const response=await managedNip05("madeira",f.deps);expect(response.status).toBe(200);expect(response.headers.get("access-control-allow-origin")).toBe("*");expect(await response.json()).toEqual({names:{madeira:active.brandPubkey}});expect(f.transport).toHaveBeenCalledWith(expect.stringContaining("nostr.json?name=madeira"),expect.objectContaining({redirect:"error",headers:expect.objectContaining({Host:"bitcoinwalk.org"})}));});
  it("does not expose queued, blocked, unknown or unrelated identities",async()=>{for(const phase of ["queued","blocked","unknown"]){const f=fixture(phase);expect(await (await managedNip05("madeira",f.deps)).json()).toEqual({names:{}});expect(f.transport).not.toHaveBeenCalled();}const f=fixture();expect(await (await managedNip05("other",f.deps)).json()).toEqual({names:{}});});
  it("proxies only bounded city LNURL paths without credentials",async()=>{const f=fixture("active"),response=await managedLnurl("madeira","/.well-known/lnurlp/madeira","",f.deps);expect(response.status).toBe(200);expect((await response.json()).tag).toBe("payRequest");expect(JSON.stringify(f.transport.mock.calls)).not.toContain("Authorization");expect((await managedLnurl("madeira","/v1/bitcoinwalk/capabilities","",f.deps)).status).toBe(404);expect((await managedLnurl("madeira","/lnurlp/../admin","",f.deps)).status).toBe(404);});
  it("fails closed on provider mismatch, oversized or unavailable responses",async()=>{const f=fixture();f.transport.mockResolvedValueOnce(new Response(JSON.stringify({names:{madeira:"b".repeat(64)}}),{headers:{"Content-Type":"application/json"}}));expect((await managedNip05("madeira",f.deps)).status).toBe(503);f.transport.mockRejectedValueOnce(new Error("offline"));expect((await managedLnurl("madeira","/lnurlp/madeira","",f.deps)).status).toBe(503);});
});
