"use client";
import {useCallback,useRef,useState} from "react";
import {useDashboard,useDashboardAutoLoad} from "../../../../components/dashboard-context";
import {isSuperAdmin} from "../../../../nostr/authority";
import {getBrowserExtensionPubkey} from "../../../../nostr/signer";
import type {RelayMonitorItem,RelayMonitorReport} from "../../../../server/relay-monitor";
import styles from "../monitoring.module.css";

const labels={green:"Healthy",amber:"Partially healthy",red:"Offline",unknown:"Unknown"} as const;
const checkLabel={ok:"passed",failed:"failed",timeout:"timed out",malformed:"malformed",unknown:"unknown"} as const;
export function RelayCards({relays}:{relays:RelayMonitorItem[]}){return <div className={styles.grid}>{relays.map(relay=><article key={relay.url} className={styles.card} data-rag={relay.status}><header><h2>{relay.purpose}</h2><span className={styles.rag} data-rag={relay.status}>{labels[relay.status]}</span></header><p><a href={relay.url.replace(/^wss:/,"https:")} target="_blank" rel="noopener noreferrer">{relay.url}</a></p><dl><div><dt>Environment</dt><dd>{relay.environment}</dd></div>{relay.cityId&&<div><dt>City ID</dt><dd>{relay.cityId}</dd></div>}<div><dt>DNS</dt><dd>{checkLabel[relay.dns]}</dd></div><div><dt>TLS</dt><dd>{checkLabel[relay.tls]}</dd></div><div><dt>HTTPS health</dt><dd>{checkLabel[relay.https]}</dd></div><div><dt>WebSocket</dt><dd>{checkLabel[relay.wss]}</dd></div><div><dt>NIP-11</dt><dd>{checkLabel[relay.nip11]}{relay.nip11Name?` — ${relay.nip11Name}`:""}</dd></div></dl>{relay.supportedNips&&<p>Capabilities: {relay.supportedNips.map(nip=>`NIP-${nip}`).join(", ")}</p>}{relay.replication&&<section className={styles.replication}><h3>Replication</h3><p>{relay.replication.state}; reconciliation {relay.replication.reconciled?"complete":"incomplete"}</p><p>{Object.entries(relay.replication.counts).map(([state,count])=>`${state} ${count}`).join(", ")||"No state rows"}</p></section>}<p className={styles.checked}>Checked {new Date(relay.checkedAt).toLocaleString()}</p></article>)}</div>;}

export default function RelaysPage(){const dashboard=useDashboard(),lock=useRef(false),[report,setReport]=useState<RelayMonitorReport>(),[message,setMessage]=useState("Checking BitcoinWalk-managed relays…"),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(lock.current||!dashboard.pubkey)return;lock.current=true;setBusy(true);try{const actor=await getBrowserExtensionPubkey();if(actor!==dashboard.pubkey||!isSuperAdmin(actor))throw new Error("Connect the BitcoinWalk super-admin identity.");const response=await fetch("/api/monitoring/relays",{headers:{"x-bitcoinwalk-dashboard-pubkey":actor},cache:"no-store"});const body=await response.json() as RelayMonitorReport|{error?:string};if(!response.ok||!("relays" in body))throw new Error("error" in body&&body.error?body.error:"Relay monitoring failed.");setReport(body);const counts=body.relays.reduce((all,item)=>({...all,[item.status]:all[item.status]+1}),{green:0,amber:0,red:0,unknown:0});setMessage(`${counts.green} healthy, ${counts.amber} partially healthy, ${counts.red} offline and ${counts.unknown} unknown.`);}catch(error){setMessage(error instanceof Error?error.message:"Relay monitoring failed.");}finally{lock.current=false;setBusy(false);}},[dashboard.pubkey]);
 useDashboardAutoLoad(load);
 return <main><p>BitcoinWalk / dashboard / monitoring / relays</p><h1>Relays</h1><p>Read-only checks cover BitcoinWalk-managed application, directory, community and city-replica transports. No Nostr signature is requested. Third-party discovery relays are intentionally excluded.</p><button type="button" disabled={busy} onClick={load}>{busy?"Checking…":"Refresh relay status"}</button><p role="status" aria-live="polite">{message}</p>{report&&<><p>Last complete check: {new Date(report.checkedAt).toLocaleString()}{report.stale?" — stale evidence; all statuses are unknown":""}</p><RelayCards relays={report.relays}/></>}</main>;}
