import {DatabaseSync} from "node:sqlite";
import {finalizeEvent,generateSecretKey,getPublicKey,nip19} from "nostr-tools";
import {describe,expect,it} from "vitest";
import {createCityDirectoryRoot} from "../nostr/city-directory";
import {DirectoryRequestStore} from "./request-store";

const cityId="ca2f9905-fb4d-4948-a12c-c792b28ec7c8";
function setup(){let now=2_000_000_000;const db=new DatabaseSync(":memory:"),store=new DirectoryRequestStore(db,()=>now);const ownerKey=generateSecretKey(),ownerPubkey=getPublicKey(ownerKey),admin=getPublicKey(generateSecretKey()),recovery=getPublicKey(generateSecretKey());const request=store.prepare({cityId,cityName:"London",cityRevisionId:"a".repeat(64),ownerPubkey,createdBy:admin,primaryRelay:"wss://london.bitcoinwalk.org/",mirrorRelays:[],operatorPubkeys:[admin]});return {store,request,ownerKey,ownerPubkey,admin,recovery,setNow:(value:number)=>now=value};}

describe("durable city directory signing requests",()=>{
 it("stores one immutable owner-signed root and makes an exact retry idempotent",()=>{const x=setup(),template=createCityDirectoryRoot({cityId,ownerPubkey:x.ownerPubkey,operatorPubkeys:[x.admin],recoveryPubkey:x.recovery,primaryRelay:"wss://london.bitcoinwalk.org/",mirrorRelays:[]},x.request.eventCreatedAt),event=finalizeEvent(template,x.ownerKey),npub=nip19.npubEncode(x.recovery);expect(x.store.sign(x.request.id,x.ownerPubkey,npub,event).signedEvent?.id).toBe(event.id);expect(x.store.sign(x.request.id,x.ownerPubkey,npub,event).signedEvent?.id).toBe(event.id);expect(()=>x.store.sign(x.request.id,x.ownerPubkey,nip19.npubEncode(getPublicKey(generateSecretKey())),event)).toThrow("exact event");});
 it("rejects wrong owners, nsec recovery input and overlapping authorities",()=>{const x=setup(),template=createCityDirectoryRoot({cityId,ownerPubkey:x.ownerPubkey,operatorPubkeys:[x.admin],recoveryPubkey:x.recovery,primaryRelay:"wss://london.bitcoinwalk.org/",mirrorRelays:[]},x.request.eventCreatedAt),event=finalizeEvent(template,x.ownerKey);expect(()=>x.store.sign(x.request.id,x.admin,nip19.npubEncode(x.recovery),event)).toThrow("verified city owner");expect(()=>x.store.sign(x.request.id,x.ownerPubkey,nip19.nsecEncode(generateSecretKey()),event)).toThrow("npub");expect(()=>x.store.sign(x.request.id,x.ownerPubkey,nip19.npubEncode(x.admin),event)).toThrow("separate offline");});
 it("expires, rejects and explicitly supersedes without deleting evidence",()=>{const x=setup();expect(()=>x.store.transition(x.request.id,x.admin,"rejected",x.admin)).toThrow("not authorized");expect(x.store.transition(x.request.id,x.ownerPubkey,"rejected",x.admin).status).toBe("rejected");const next=x.store.prepare({cityId,cityName:"London",cityRevisionId:"b".repeat(64),ownerPubkey:x.ownerPubkey,createdBy:x.admin,primaryRelay:"wss://london.bitcoinwalk.org/",mirrorRelays:[],operatorPubkeys:[x.admin]});expect(x.store.transition(next.id,x.admin,"superseded",x.admin).status).toBe("superseded");const expiring=x.store.prepare({cityId,cityName:"London",cityRevisionId:"c".repeat(64),ownerPubkey:x.ownerPubkey,createdBy:x.admin,primaryRelay:"wss://london.bitcoinwalk.org/",mirrorRelays:[],operatorPubkeys:[x.admin],ttl:300});x.setNow(expiring.expiresAt);expect(x.store.get(expiring.id)?.status).toBe("expired");});
});
