import {readFileSync} from "node:fs";
import {describe,it,expect} from "vitest";
import {dashboardAccess,dashboardNavigation} from "../../../../domain/dashboard";
describe("admin sponsor tools",()=>{
 it("starts with Assign Existing Sponsor without the introductory block",()=>{const page=readFileSync("src/app/admin/sponsors/page.tsx","utf8");expect(page).toContain('return <main><section><h1>Assign Existing Sponsor</h1>');expect(page).not.toContain('BitcoinWalk / dashboard / sponsors');expect(page).not.toContain('Sponsor assignments loaded.');expect(page).not.toContain('Browse sponsor assets</a>');expect(page).not.toContain('"Loading…":"Refresh"');expect(page).toContain('{message&&<p role="status">{message}</p>}');});
 it("uses CityFinder, scope toggle and display radios with visible artwork guidance",()=>{const page=readFileSync("src/app/admin/sponsors/page.tsx","utf8");expect(page).toContain('<CityFinder');expect(page).toContain('name="sponsor-scope"');expect(page).toContain('name="sponsor-display"');expect(page).not.toContain('<label>Scope<select');expect(page).not.toContain('<label>Display<select');expect(page).toContain('<SponsorPicker');expect(page).not.toContain('Upload and replace logo');expect(page).not.toContain('Use website from Nostr profile');expect(page).not.toContain('<h2>Logo artwork</h2>');expect(page).toContain('<SponsorAssetLibrary');});
 it("leaves the city lookup empty until the administrator chooses a city",()=>{const page=readFileSync("src/app/admin/sponsors/page.tsx","utf8");expect(page).toContain('setCityId(value=>approved.some(w=>w.revision.city.cityId===value)?value:"")');expect(page).not.toContain('approved[0]?.revision.city.cityId');});
 it("replaces source artwork before assignment and creates a merged preview",()=>{const page=readFileSync("src/app/admin/sponsors/page.tsx","utf8");expect(page).not.toContain('Save this sponsor assignment first');expect(page).toContain('cityId={selectedSponsor.cityId}');expect(page).toContain('scopeKey={selectedSponsor.scopeKey}');expect(page).toContain('>Create merged image</button>');expect(page).toContain('action:"generate-sponsor-composite"');});
 it("places the selected logo directly below the website field",()=>{const page=readFileSync("src/app/admin/sponsors/page.tsx","utf8");const website=page.indexOf('<label>Approved sponsor website'),preview=page.indexOf('<SponsorLogoPreview');expect(website).toBeGreaterThan(0);expect(preview).toBeGreaterThan(website);expect(page).not.toContain('Review the saved website before signing');expect(page).toContain('No approved logo has been uploaded for this sponsor.');});
 it("maps the catalogue logo hash into the selected preview state",()=>{const page=readFileSync("src/app/admin/sponsors/page.tsx","utf8");expect(page).toContain('setSelectedSponsor(entry?{hash:entry.logoHash,pubkey:entry.pubkey,cityId:entry.cityId,scopeKey:entry.scopeKey}:null)');expect(page).not.toContain('setSelectedSponsor(entry);');});
 it("puts format guidance in a collapsed accordion before the file chooser",()=>{const upload=readFileSync("src/components/sponsor-logo-upload.tsx","utf8");const details=upload.indexOf('<details><summary>What logo format and size should I use?</summary>'),chooser=upload.indexOf('<label>Choose logo file');expect(details).toBeGreaterThan(0);expect(chooser).toBeGreaterThan(details);expect(upload).toContain("1024 × 256 pixels");expect(upload).toContain("640 × 160 pixels");expect(upload).toContain("320 × 80 pixels");expect(upload).toContain("aspect ratio close to 4:1");expect(upload).not.toContain("Refresh connection and assignments");expect(upload).not.toContain("Connect Nostr signer");expect(upload).not.toContain("<h2>Upload sponsor logo</h2>");});
 it("loads the selected assignment without requesting the extension identity",()=>{const upload=readFileSync("src/components/sponsor-logo-upload.tsx","utf8");const loader=upload.slice(upload.indexOf("async function loadAssignments"),upload.indexOf("async function upload"));expect(loader).toContain("dashboard.pubkey");expect(loader).not.toContain("getBrowserExtensionPubkey");expect(upload).toContain("useDashboardAutoLoad(loadAssignments)");});
 it("tells the super-admin to review and sign after upload without referring to another administrator",()=>{const upload=readFileSync("src/components/sponsor-logo-upload.tsx","utf8");expect(upload).toContain("Review the image below, then sign to approve this exact asset.");expect(upload).toContain("Uploading and approval are separate signed actions.");expect(upload).not.toContain("Pending super-admin approval");expect(upload).not.toContain("approved by the BitcoinWalk super-admin");});
 it("merges assignment, upload and review on the single Sponsors page",()=>{expect(dashboardNavigation("super-admin").filter(row=>row.href.startsWith("/admin/sponsors"))).toHaveLength(1);const page=readFileSync("src/app/admin/sponsors/page.tsx","utf8");expect(page).toContain('<SponsorLogoUpload');expect(page).toContain('<SponsorLogoReview');expect(page).toContain('scopeKey={selectedSponsor.scopeKey}');expect(readFileSync("src/app/admin/sponsors/layout.tsx","utf8")).toContain('All sponsors and payments');});
 it.each(["/admin/sponsors","/admin/sponsors/upload","/admin/sponsors/logos"])("restricts %s to super-admin",route=>{expect(dashboardAccess(route,"super-admin")).toBe(true);expect(dashboardAccess(route,"organizer")).toBe(false);expect(dashboardAccess(route,"member")).toBe(false);expect(dashboardAccess(route,"disconnected")).toBe(false);});
 it("redirects all old URLs to the unified page",()=>{for(const path of ["src/app/sponsor/logo/page.tsx","src/app/admin/sponsors/upload/page.tsx","src/app/admin/sponsors/logos/page.tsx"]){const page=readFileSync(path,"utf8");expect(page).toContain('redirect("/admin/sponsors")');expect(page).not.toContain('type="file"');}});
 it("binds artwork tools to the selected assignment instead of showing extra city selectors",()=>{const upload=readFileSync("src/components/sponsor-logo-upload.tsx","utf8"),review=readFileSync("src/components/sponsor-logo-review.tsx","utf8");expect(upload).toContain('row.sponsorship.scope.cityId===cityId');expect(upload).toContain('row.sponsorship.sponsorPubkey===sponsorPubkey');expect(review).toContain('sponsorshipKey(row.sponsorship.scope)===scopeKey');expect(upload).not.toContain('<select');expect(review).not.toContain('<select');});
});
