import {readFileSync} from "node:fs";
import {describe,it,expect} from "vitest";
import {dashboardAccess,dashboardNavigation} from "../../../../domain/dashboard";
describe("admin sponsor tools",()=>{
 it("starts with Assign Existing Sponsor without the introductory block",()=>{const page=readFileSync("src/app/admin/sponsors/page.tsx","utf8");expect(page).toContain('return <main><section><h1>Assign Existing Sponsor</h1>');expect(page).not.toContain('BitcoinWalk / dashboard / sponsors');expect(page).not.toContain('Sponsor assignments loaded.');expect(page).not.toContain('Browse sponsor assets</a>');expect(page).not.toContain('"Loading…":"Refresh"');expect(page).toContain('{message&&<p role="status">{message}</p>}');});
 it("uses CityFinder, scope toggle and display radios with visible artwork guidance",()=>{const page=readFileSync("src/app/admin/sponsors/page.tsx","utf8");expect(page).toContain('<CityFinder');expect(page).toContain('name="sponsor-scope"');expect(page).toContain('name="sponsor-display"');expect(page).not.toContain('<label>Scope<select');expect(page).not.toContain('<label>Display<select');expect(page).toContain('<SponsorPicker');expect(page).toContain('Upload and replace logo');expect(page).not.toContain('Use website from Nostr profile');expect(page).not.toContain('<h2>Logo artwork</h2>');expect(page).toContain('<SponsorAssetLibrary');});
 it("replaces source artwork before assignment and creates a merged preview",()=>{const page=readFileSync("src/app/admin/sponsors/page.tsx","utf8");expect(page).not.toContain('Save this sponsor assignment first');expect(page).toContain('cityId={selectedSponsor.cityId}');expect(page).toContain('scopeKey={selectedSponsor.scopeKey}');expect(page).toContain('>Create merged image</button>');expect(page).toContain('action:"generate-sponsor-composite"');});
 it("places the selected logo directly below the website field",()=>{const page=readFileSync("src/app/admin/sponsors/page.tsx","utf8");const website=page.indexOf('<label>Approved sponsor website'),preview=page.indexOf('<SponsorLogoPreview');expect(website).toBeGreaterThan(0);expect(preview).toBeGreaterThan(website);expect(page).not.toContain('Review the saved website before signing');expect(page).toContain('No approved logo has been uploaded for this sponsor.');});
 it("merges assignment, upload and review on the single Sponsors page",()=>{expect(dashboardNavigation("super-admin").filter(row=>row.href.startsWith("/admin/sponsors"))).toHaveLength(1);const page=readFileSync("src/app/admin/sponsors/page.tsx","utf8");expect(page).toContain('<SponsorLogoUpload');expect(page).toContain('<SponsorLogoReview');expect(page).toContain('scopeKey={selectedSponsor.scopeKey}');expect(readFileSync("src/app/admin/sponsors/layout.tsx","utf8")).not.toContain('<nav');});
 it.each(["/admin/sponsors","/admin/sponsors/upload","/admin/sponsors/logos"])("restricts %s to super-admin",route=>{expect(dashboardAccess(route,"super-admin")).toBe(true);expect(dashboardAccess(route,"organizer")).toBe(false);expect(dashboardAccess(route,"member")).toBe(false);expect(dashboardAccess(route,"disconnected")).toBe(false);});
 it("redirects all old URLs to the unified page",()=>{for(const path of ["src/app/sponsor/logo/page.tsx","src/app/admin/sponsors/upload/page.tsx","src/app/admin/sponsors/logos/page.tsx"]){const page=readFileSync(path,"utf8");expect(page).toContain('redirect("/admin/sponsors")');expect(page).not.toContain('type="file"');}});
 it("binds artwork tools to the selected assignment instead of showing extra city selectors",()=>{const upload=readFileSync("src/components/sponsor-logo-upload.tsx","utf8"),review=readFileSync("src/components/sponsor-logo-review.tsx","utf8");expect(upload).toContain('row.sponsorship.scope.cityId===cityId');expect(upload).toContain('row.sponsorship.sponsorPubkey===sponsorPubkey');expect(review).toContain('sponsorshipKey(row.sponsorship.scope)===scopeKey');expect(upload).not.toContain('<select');expect(review).not.toContain('<select');});
});
