"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {QRCodeSVG} from "qrcode.react";
import {nip19} from "nostr-tools";
import CityFinder from "../../components/city-finder";
import OrganizerIdentity from "../../components/organizer-identity";
import {SUPER_ADMIN_NPUB} from "../../domain/city";
import {SPONSOR_PACKAGES,type SponsorCity,type SponsorOrder} from "../../payments/sponsor-types";
import {sponsorRequest} from "../../payments/sponsor-auth";
import {signForOrganizer} from "../../nostr/organizer-identity";
import styles from "./sponsor.module.css";
const STORAGE="bitcoinwalk-sponsor-checkout-v1";
type Saved={token:string;id?:string;cityId:string;count:number;ids:string[]};
async function post(body:unknown){const response=await fetch("/api/sponsorships",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body),cache:"no-store",signal:AbortSignal.timeout(60000)}),result=await response.json();if(!response.ok)throw Object.assign(new Error(result.error||"Sponsorship unavailable."),{selectionRejected:result.selectionRejected});return result as {order:SponsorOrder};}
export default function SponsorCheckout({initialCity}:{initialCity:string}){
 const [cities,setCities]=useState<SponsorCity[]>([]),[cityId,setCityId]=useState(""),[count,setCount]=useState(0),[ids,setIds]=useState<string[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[order,setOrder]=useState<SponsorOrder|null>(null),[saved,setSaved]=useState<Saved|null>(null),[identity,setIdentity]=useState<string|null>(null);
 const lock=useRef(false),identityChanged=useCallback((key:string|null)=>setIdentity(key),[]);
 const load=useCallback(async()=>{setLoading(true);try{const response=await fetch("/api/sponsorships",{cache:"no-store"}),data=await response.json();if(!response.ok)throw new Error(data.error);setCities(data.cities);setCityId(current=>current||data.cities.find((city:SponsorCity)=>[city.name,city.slug,city.id].some(value=>value.toLocaleLowerCase()===initialCity.toLocaleLowerCase()))?.id||"");setError("");}catch(e){setError(e instanceof Error?e.message:"Could not load cities.");}finally{setLoading(false);}},[initialCity]);
 useEffect(()=>{let active=true;queueMicrotask(()=>{if(!active)return;void load();try{const existing=JSON.parse(localStorage.getItem(STORAGE)||"null") as Saved|null;if(existing&&/^[a-f0-9]{64}$/.test(existing.token)){setSaved(existing);setCityId(existing.cityId);setCount(existing.count);setIds(existing.ids);if(existing.id)void post({action:"status",id:existing.id,token:existing.token}).then(result=>setOrder(result.order)).catch(e=>setError(e.message));}}catch{setError("Allow browser storage to keep your payment recoverable.");}});return()=>{active=false;};},[load]);
 async function run(work:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError("");try{await work();}catch(e){setError(e instanceof Error?e.message:"Please retry.");}finally{lock.current=false;setBusy(false);}}
 const refresh=useCallback(async()=>{if(!saved?.id||lock.current)return;lock.current=true;try{const result=await post({action:"status",id:saved.id,token:saved.token});setOrder(result.order);setError("");}catch(e){setError(e instanceof Error?e.message:"Payment check unavailable.");}finally{lock.current=false;}},[saved]);
 useEffect(()=>{if(!saved?.id||order?.status==="paid"||order?.status==="expired")return;const timer=setInterval(()=>void refresh(),15000);return()=>clearInterval(timer);},[saved,order?.status,refresh]);
 async function next(){await run(async()=>{const selection=saved??{token:Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,"0")).join(""),cityId,count,ids};localStorage.setItem(STORAGE,JSON.stringify(selection));setSaved(selection);let result:{order:SponsorOrder};try{result=await post({action:"create",token:selection.token,cityId:selection.cityId,count:selection.count,ids:selection.ids});}catch(e){if((e as {selectionRejected?:boolean}).selectionRejected){localStorage.removeItem(STORAGE);setSaved(null);}throw e;}const updated={...selection,id:result.order.id};localStorage.setItem(STORAGE,JSON.stringify(updated));setSaved(updated);setOrder(result.order);});}
 function reset(){localStorage.removeItem(STORAGE);setSaved(null);setOrder(null);setIds([]);setCount(0);void load();}
 const city=cities.find(c=>c.id===cityId),locked=busy||!!saved;
 return <section aria-label="Sponsorship booking"><p>Choose your city, package and dates. Pay with Lightning, then connect or create your Nostr identity.</p>{!order?<>
  <CityFinder items={cities.map(city=>({id:city.id,name:city.name,keywords:[city.slug],meta:`${city.walks.length} available walks`}))} value={cityId} disabled={loading||locked} onChange={id=>{setCityId(id);setCount(0);setIds([]);const url=new URL(window.location.href),selected=cities.find(c=>c.id===id);if(selected)url.searchParams.set("city",selected.name);else url.searchParams.delete("city");window.history.replaceState(null,"",url);}}/>
  {loading&&<p role="status">Loading cities and upcoming walks…</p>}
  {city&&!city.walks.length&&<p>No walks are available to sponsor in {city.name} yet. Choose another city or <a href={`https://armada.buzz/dms/${SUPER_ADMIN_NPUB}`} target="_blank" rel="noreferrer">contact BitcoinWalk about future dates</a>.</p>}
  {city&&city.walks.length>0&&<><fieldset disabled={locked}><legend>Choose your package</legend><div className={styles.packages}>{SPONSOR_PACKAGES.map(pack=><label className={`${styles.package} ${pack.count===5?styles.recommended:""}`} key={pack.count}><input type="radio" name="package" checked={count===pack.count} disabled={city.walks.length<pack.count} onChange={()=>{setCount(pack.count);setIds([]);}}/><span>{pack.count} {pack.count===1?"walk":"walks"}</span><strong className={styles.price}>{pack.sats.toLocaleString("en-GB")} sats</strong>{pack.count===5&&<span className={styles.badge}>Recommended</span>}{city.walks.length<pack.count&&<small>Needs {pack.count} available dates</small>}</label>)}</div></fieldset>{count>0&&<fieldset disabled={locked}><legend>Choose {count} {count===1?"walk":"walks"} · {ids.length}/{count} selected</legend><div className={styles.walks}>{city.walks.map(walk=><label key={walk.id}><input type="checkbox" checked={ids.includes(walk.id)} disabled={!ids.includes(walk.id)&&ids.length>=count} onChange={e=>setIds(current=>e.target.checked?[...current,walk.id]:current.filter(id=>id!==walk.id))}/><span>{walk.label}</span></label>)}</div></fieldset>}</>}
  <button type="button" disabled={busy||!cityId||!count||ids.length!==count} onClick={()=>void next()}>{busy?"Preparing invoice…":saved?"Recover checkout":"Next — pay with Lightning"}</button>
 </>:<><h2>{order.cityName} · {order.count} {order.count===1?"walk":"walks"} · {(order.amountMsat/1000).toLocaleString("en-GB")} sats</h2><ul>{order.walks.map(walk=><li key={walk.id}>{walk.label}</li>)}</ul>
  {order.status==="pending"&&<><h3>Pay with Lightning</h3><QRCodeSVG value={`lightning:${order.invoice}`} size={280} marginSize={2} title="Sponsorship Lightning invoice"/><p><a href={`lightning:${order.invoice}`}>Open Lightning wallet</a></p><label>Invoice<textarea readOnly rows={3} value={order.invoice}/></label><button onClick={()=>void navigator.clipboard.writeText(order.invoice).catch(()=>setError("Copy the invoice from the field above."))}>Copy invoice</button><p>Expires {new Date(order.expiresAt*1000).toLocaleString()}. Payment is checked automatically.</p><button onClick={()=>void refresh()}>Check payment</button></>}
  {order.status==="expired"&&<><p>This invoice expired. Check payment once more if you already paid, otherwise choose available dates again.</p><button onClick={()=>void refresh()}>Check payment</button><button onClick={reset}>Choose again</button></>}
  {(order.status==="creating"||order.status==="creation-uncertain")&&<p>Your invoice could not be confirmed. Your order is saved; contact BitcoinWalk with order {order.id} before starting another booking.</p>}
  {order.status==="paid"&&!order.pubkey&&<><p role="status"><strong>Payment confirmed. Finish by connecting your Nostr identity.</strong></p><OrganizerIdentity disabled={busy} onIdentityChange={identityChanged} heading="Your sponsor identity" intro="Connect your Nostr identity or create a new one to associate with this payment."/><button disabled={!identity||busy} onClick={()=>void run(async()=>{const event=await signForOrganizer(sponsorRequest("claim",window.location.origin,order.id),identity!);const result=await post({action:"claim",id:order.id,token:saved!.token,event});setOrder(result.order);})}>Finish — associate my identity</button></>}
  {order.status==="paid"&&order.pubkey&&<><p role="status"><strong>Your sponsorship payment and identity are confirmed.</strong></p><code className={styles.key}>{nip19.npubEncode(order.pubkey)}</code><p>BitcoinWalk will review your sponsor details and artwork for the selected walks.</p><button onClick={reset}>Sponsor more walks</button></>}
  {order.needsReview&&<p>Your payment is confirmed, but the selected dates need a BitcoinWalk review. Contact us with your order ID.</p>}
  <p>Order: <code>{order.id}</code></p>{order.paymentHash&&<p className={styles.key}>Payment hash: <code>{order.paymentHash}</code></p>}
  <button type="button" onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(saved)],{type:"application/json"})),a=document.createElement("a");a.href=url;a.download="bitcoinwalk-sponsor-recovery.json";a.click();URL.revokeObjectURL(url);}}>Save private checkout recovery file</button>
 </>}{error&&<p role="alert">{error}</p>}{!order&&error&&<button onClick={()=>void load()}>Refresh cities</button>}<details><summary>Recover an existing checkout</summary><label>Choose your private recovery file<input type="file" accept="application/json,.json" onChange={event=>{const file=event.target.files?.[0];if(!file)return;void run(async()=>{if(file.size>8192)throw new Error("Invalid recovery file.");const value=JSON.parse(await file.text()) as Saved;if(!value.id||!/^[a-f0-9]{64}$/.test(value.token))throw new Error("Invalid recovery file.");const result=await post({action:"status",id:value.id,token:value.token});localStorage.setItem(STORAGE,JSON.stringify(value));setSaved(value);setOrder(result.order);});}}/></label></details></section>;
}
