#!/bin/sh
set -eu
service=bitcoinwalk-rustress-payout;old="$service-disabled-0.2.10";version=0.2.11;image="$service:$version";root="$HOME/.local/state/bitcoinwalk-rustress";state="$root/payout-service";secrets="$root/secrets";config="$root/payout-config";mode="$root/payout-mode"
fail(){ echo 'Invoice-only service installation failed.' >&2;exit 1;};test "$(id -u)" -ne 0&&test "$(id -un)" = bitcoinwalk||fail;umask 077
test "$(docker inspect "$service" --format '{{index .Config.Labels "org.bitcoinwalk.version"}}|{{index .Config.Labels "org.bitcoinwalk.mode"}}|{{.HostConfig.NetworkMode}}|{{.State.Status}}')" = '0.2.10|disabled|none|running'||fail
test "$(tr -d '\n'<"$mode")" = disabled||fail;for name in nwc-uri intake-api-token issuer-api-token receipt-api-token authority-api-token operations-api-token;do path="$secrets/$name";test -f "$path"&&test ! -L "$path"&&test "$(stat -c '%U:%G:%a' "$path")" = bitcoinwalk:bitcoinwalk:600||fail;done
path="$config/checkout-client-pubkey";test -f "$path"&&test ! -L "$path"&&test "$(stat -c '%U:%G:%a' "$path")" = bitcoinwalk:bitcoinwalk:600||fail
test -f rustress-payout-service-0.2.11.cjs&&test -f Dockerfile;test "$(sha256sum rustress-payout-service-0.2.11.cjs|cut -d' ' -f1)" = da15fa93546f792937214b5c025950498ecf772734dd14d70cd080271c73d7b7||fail
docker build --pull=false --network=none -f Dockerfile -t "$image" . >/dev/null||fail
temporary="$root/.payout-mode.$$";printf '%s\n' invoice-only>"$temporary";chmod 600 "$temporary"
rollback(){ docker rm -f "$service" >/dev/null 2>&1||true;mv -f "$temporary" "$mode" 2>/dev/null||true;printf '%s\n' disabled>"$mode";chmod 600 "$mode";if docker inspect "$old" >/dev/null 2>&1;then docker rename "$old" "$service";docker start "$service" >/dev/null;fi;fail;}
docker stop "$service" >/dev/null;docker rename "$service" "$old";mv "$temporary" "$mode";trap rollback EXIT HUP INT TERM
mounts="--mount type=bind,src=$secrets/nwc-uri,dst=/run/bitcoinwalk-secrets/nwc-uri,readonly --mount type=bind,src=$secrets/intake-api-token,dst=/run/bitcoinwalk-secrets/intake-api-token,readonly --mount type=bind,src=$secrets/issuer-api-token,dst=/run/bitcoinwalk-secrets/issuer-api-token,readonly --mount type=bind,src=$secrets/receipt-api-token,dst=/run/bitcoinwalk-secrets/receipt-api-token,readonly --mount type=bind,src=$secrets/authority-api-token,dst=/run/bitcoinwalk-secrets/authority-api-token,readonly --mount type=bind,src=$secrets/operations-api-token,dst=/run/bitcoinwalk-secrets/operations-api-token,readonly --mount type=bind,src=$config/checkout-client-pubkey,dst=/run/bitcoinwalk-config/checkout-client-pubkey,readonly --mount type=bind,src=$mode,dst=/run/bitcoinwalk-config/payout-mode,readonly --mount type=bind,src=$state,dst=/var/lib/bitcoinwalk-payout"
# shellcheck disable=SC2086
docker run -d --name "$service" --restart unless-stopped --network host --label org.bitcoinwalk.service=rustress-payout --label org.bitcoinwalk.mode=invoice-only --label org.bitcoinwalk.version="$version" --user 0:0 --read-only --tmpfs /tmp:rw,noexec,nosuid,nodev,size=8m --cap-drop ALL --security-opt no-new-privileges:true --pids-limit 64 --memory 256m --cpus 0.25 $mounts --env NODE_ENV=production "$image" >/dev/null
ready=0;i=0;while test "$i" -lt 30;do if curl -fsS --max-time 3 http://127.0.0.1:8893/health >/dev/null 2>&1;then ready=1;break;fi;i=$((i+1));sleep 2;done;test "$ready" -eq 1
authority=$(cat "$secrets/authority-api-token");for name in endo donate;do body="{\"version\":1,\"domain\":\"bitcoinwalk.org\",\"localPart\":\"$name\",\"walletRef\":\"bitcoinwalk-rustress\",\"receivingDestination\":\"bitcoinwalk@getalby.com\",\"invoiceIssuance\":\"enabled\"}";result=$(curl -fsS --max-time 10 -H "Authorization: Bearer $authority" -H 'Content-Type: application/json' --data "$body" http://127.0.0.1:8893/v1/retained-address-authority);echo "$result"|grep -q '"state":"recorded"';echo "$result"|grep -q "\"localPart\":\"$name\"";done
test "$(docker inspect "$service" --format '{{index .Config.Labels "org.bitcoinwalk.version"}}|{{index .Config.Labels "org.bitcoinwalk.mode"}}|{{.HostConfig.NetworkMode}}|{{.State.Status}}')" = '0.2.11|invoice-only|host|running'
docker rm "$old" >/dev/null;trap - EXIT HUP INT TERM;echo 'RUSTRESS_INVOICE_ONLY_0.2.11_OK'
