"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {nip19,type Event} from "nostr-tools";
import {useDashboard,useDashboardAutoLoad} from "../../../components/dashboard-context";
import {approvedCalendarWalks,calendarEventSource,calendarOccurrence} from "../../../nostr/calendar-records";
import {queryCalendarEvents} from "../../../nostr/city-records";
import {isSuperAdmin} from "../../../nostr/authority";
import {authenticateWithBrowserExtension,getBrowserExtensionPubkey,signWithBrowserExtension} from "../../../nostr/signer";
import {assertExactSigned} from "../../../nostr/moderation";
import {publishVerifiedEvent} from "../../../nostr/relay";
import {relayConfig} from "../../../lib/relay-config";
import {calendarAddress,createSponsorshipRevision,latestSponsorships,querySponsorships,sponsorshipKey,type SponsorshipRevision} from "../../../nostr/sponsorships";
import {safeProfileWebsite,watchPublicProfiles} from "../../../nostr/profiles";
import type {Sponsorship} from "../../../domain/sponsorship";

type WalkOption={event:Event;cityId:string;address:string;label:string};
function pubkey(value:string):string{const clean=value.trim();if(/^[0-9a-f]{64}$/.test(clean))return clean;try{const decoded=nip19.decode(clean);if(decoded.type==="npub")return decoded.data;}catch{}throw new Error("Enter a valid sponsor npub.");}
function localEpoch(value:string):number|undefined{if(!value)return;const time=new Date(value).getTime();if(!Number.isFinite(time))throw new Error("Enter a valid sponsorship date.");return Math.floor(time/1000);}
export default function SponsorsPage(){
 const dashboard=useDashboard(),lock=useRef(false),[rows,setRows]=useState<SponsorshipRevision[]>([]),[walks,setWalks]=useState<WalkOption[]>([]),[scope,setScope]=useState<"city"|"walk">("city"),[cityId,setCityId]=useState(""),[address,setAddress]=useState(""),[mode,setMode]=useState<Sponsorship["mode"]>("empty"),[identity,setIdentity]=useState(""),[website,setWebsite]=useState(""),[startsAt,setStartsAt]=useState(""),[endsAt,setEndsAt]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("Connect the super-admin identity to manage sponsors.");
 const cities=useMemo(()=>approvedCalendarWalks(dashboard.directory?.revisions??[],dashboard.directory?.approvals??[]),[dashboard.directory]),cityWalks=useMemo(()=>walks.filter(walk=>walk.cityId===cityId),[walks,cityId]);
 const load=useCallback(async(force=false)=>{if((lock.current&&!force)||!dashboard.pubkey||!dashboard.directory)return;if(!force)lock.current=true;setBusy(true);try{const actor=await getBrowserExtensionPubkey();if(!isSuperAdmin(actor)||actor!==dashboard.pubkey)throw new Error("Connect the BitcoinWalk super-admin identity.");const approved=approvedCalendarWalks(dashboard.directory.revisions,dashboard.directory.approvals),[sponsorships,events]=await Promise.all([querySponsorships(relayConfig.readRelays),queryCalendarEvents(relayConfig.readRelays,{cityIds:approved.map(w=>w.revision.city.cityId)})]);const options:WalkOption[]=[];for(const event of events){const walk=approved.find(item=>calendarEventSource(event,item));const addressValue=calendarAddress(event),occurrence=calendarOccurrence(event);if(walk&&addressValue&&occurrence)options.push({event,cityId:walk.revision.city.cityId,address:addressValue,label:`${walk.revision.city.cityName} · ${new Date(occurrence.start*1000).toLocaleString()}`});}setRows(sponsorships);setWalks(options.sort((a,b)=>a.label.localeCompare(b.label)));setCityId(value=>approved.some(w=>w.revision.city.cityId===value)?value:approved[0]?.revision.city.cityId??"");setMessage("Sponsor assignments loaded. Every change requires the super-admin signature.");}catch(error){setMessage(error instanceof Error?error.message:"Could not load sponsors.");}finally{lock.current=false;setBusy(false);}},[dashboard.pubkey,dashboard.directory]);
 useDashboardAutoLoad(load);
 useEffect(()=>{let active=true;queueMicrotask(()=>{if(active&&scope==="walk"&&!cityWalks.some(w=>w.address===address))setAddress(cityWalks[0]?.address??"");});return()=>{active=false;};},[scope,address,cityWalks]);
 const key=scope==="city"?`city:${cityId}`:`walk:${cityId}:${address}`,current=latestSponsorships(rows).find(row=>sponsorshipKey(row.sponsorship.scope)===key);
 useEffect(()=>{let active=true;const value=current?.sponsorship;queueMicrotask(()=>{if(!active)return;setMode(value?.mode??(scope==="city"?"empty":"inherit"));setIdentity(value?.sponsorPubkey?nip19.npubEncode(value.sponsorPubkey):"");setWebsite(value?.website??"");setStartsAt(value?.startsAt?new Date(value.startsAt*1000).toISOString().slice(0,16):"");setEndsAt(value?.endsAt?new Date(value.endsAt*1000).toISOString().slice(0,16):"");});return()=>{active=false;};},[key,current,scope]);
 async function fromProfile(){try{const key=pubkey(identity);setMessage("Reading the sponsor’s public Nostr profile…");await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>{stop();reject(new Error("No safe HTTPS website was found in the sponsor’s Nostr profile."));},7000),stop=watchPublicProfiles([key],(_key,profile)=>{const safe=safeProfileWebsite(profile.website);if(!safe)return;clearTimeout(timer);stop();setWebsite(safe);resolve();});});setMessage("Website copied from the sponsor’s signed Nostr profile. Review it before signing.");}catch(error){setMessage(error instanceof Error?error.message:"Could not read the sponsor profile.");}}
 async function publish(nextMode=mode){if(lock.current||!cityId||scope==="walk"&&!address)return;lock.current=true;setBusy(true);try{const actor=await getBrowserExtensionPubkey();if(!isSuperAdmin(actor)||actor!==dashboard.pubkey)throw new Error("Connect the BitcoinWalk super-admin identity.");const sponsorPubkey=nextMode==="sponsor"?pubkey(identity):undefined,safeWebsite=nextMode==="sponsor"&&website?safeProfileWebsite(website):undefined;if(nextMode==="sponsor"&&website&&!safeWebsite)throw new Error("Sponsor website must be a public HTTPS URL.");const value={version:1 as const,scope:scope==="city"?{type:"city" as const,cityId}:{type:"walk" as const,cityId,address},mode:nextMode,...(sponsorPubkey?{sponsorPubkey}:{}),...(safeWebsite?{website:safeWebsite}:{}),...(localEpoch(startsAt)!==undefined?{startsAt:localEpoch(startsAt)}:{}),...(localEpoch(endsAt)!==undefined?{endsAt:localEpoch(endsAt)}:{}),...(current?{previousRevisionId:current.event.id}:{})};const template=createSponsorshipRevision(value);setMessage("Review and sign this sponsorship change in your extension…");const signed=await signWithBrowserExtension(template);assertExactSigned(signed,template);const result=await publishVerifiedEvent(signed,relayConfig.writeRelays,1,authenticateWithBrowserExtension);setMessage(`Sponsor assignment published to ${result.accepted.length} relay(s).`);await load(true);}catch(error){setMessage(error instanceof Error?error.message:"Sponsor assignment could not be published.");}finally{lock.current=false;setBusy(false);}}
 return <main><p>BitcoinWalk / dashboard / sponsors</p><h1>Sponsors</h1><p>Manage the signed sponsor shown for a whole city or override one walk. Walk assignments take precedence over city assignments.</p><p role="status">{message}</p><button disabled={busy} onClick={()=>void load(true)}>{busy?"Loading…":"Refresh"}</button><section><h2>Assignment</h2><label>Scope<select value={scope} disabled={busy} onChange={event=>setScope(event.target.value as "city"|"walk")}><option value="city">City</option><option value="walk">Individual walk</option></select></label><label>City<select value={cityId} disabled={busy} onChange={event=>setCityId(event.target.value)}>{cities.map(walk=><option key={walk.revision.city.cityId} value={walk.revision.city.cityId}>{walk.revision.city.cityName}</option>)}</select></label>{scope==="walk"&&<label>Walk<select value={address} disabled={busy} onChange={event=>setAddress(event.target.value)}>{cityWalks.map(walk=><option key={walk.event.id} value={walk.address}>{walk.label}</option>)}</select></label>}<label>Display<select value={mode} disabled={busy} onChange={event=>setMode(event.target.value as Sponsorship["mode"])}>{scope==="walk"&&<option value="inherit">Use city sponsor</option>}<option value="hidden">Hide sponsorship module</option><option value="empty">Show sponsor invitation</option><option value="sponsor">Show assigned sponsor</option></select></label>{mode==="sponsor"&&<><label>Sponsor npub<input value={identity} disabled={busy} onChange={event=>setIdentity(event.target.value)} placeholder="npub1…"/></label><label>Approved sponsor website<input value={website} disabled={busy} onChange={event=>setWebsite(event.target.value)} placeholder="https://…"/></label><button type="button" disabled={busy||!identity} onClick={()=>void fromProfile()}>Use website from Nostr profile</button><p>The approved HTTPS URL is snapshotted in the signed assignment. Later profile edits cannot silently redirect this link.</p><label>Starts (optional)<input type="datetime-local" value={startsAt} disabled={busy} onChange={event=>setStartsAt(event.target.value)}/></label><label>Ends (optional)<input type="datetime-local" value={endsAt} disabled={busy} onChange={event=>setEndsAt(event.target.value)}/></label></>}<p>Current state: <strong>{current?.sponsorship.mode??"not configured"}</strong></p><button disabled={busy} onClick={()=>void publish()}>{busy?"Publishing…":"Sign and save assignment"}</button>{current?.sponsorship.mode==="sponsor"&&<> <button disabled={busy} onClick={()=>void publish("empty")}>Clear sponsor</button></>}{scope==="walk"&&current?.sponsorship.mode!=="inherit"&&<> <button disabled={busy} onClick={()=>void publish("inherit")}>Use city sponsor</button></>}</section><section><h2>Precedence</h2><p>The global Sponsorships feature flag is controlled under Content. When it is off, all modules stay hidden without deleting assignments. An individual walk can inherit, hide, invite, or replace its city sponsor.</p></section></main>;
}
