"use client";
import {useRef,useState} from "react";
import {useDashboard,useDashboardAutoLoad} from "../../../components/dashboard-context";
import {mediaAlerts,replicationStatus,type MediaAlert,type ReplicationStatus} from "../../../lib/media-client";
import {getBrowserExtensionPubkey} from "../../../nostr/signer";
import {isSuperAdmin} from "../../../nostr/authority";
export default function AlertsPage(){const dashboard=useDashboard(),lock=useRef(false),[alerts,setAlerts]=useState<MediaAlert[]>([]),[replication,setReplication]=useState<ReplicationStatus>(),[checkedAt,setCheckedAt]=useState(""),[message,setMessage]=useState("Connect the super-admin identity to check operational alerts."),[busy,setBusy]=useState(false);
 async function load(){if(lock.current||!dashboard.pubkey)return;lock.current=true;setBusy(true);try{const actor=await getBrowserExtensionPubkey();if(!isSuperAdmin(actor)||actor!==dashboard.pubkey)throw new Error("Connect the BitcoinWalk super-admin identity.");setMessage("Approve the operational-alert check in your signer…");const [media,replica]=await Promise.all([mediaAlerts(),replicationStatus()]);setAlerts(media.alerts);setReplication(replica.report);setCheckedAt(replica.checkedAt);const degraded=replica.report.cities.filter(city=>city.state==="degraded").length;setMessage(degraded||media.alerts.length?`${media.alerts.length} media and ${degraded} replication alert(s) require attention.`:"Media integrity and replication status are healthy.");}catch(error){setMessage(error instanceof Error?error.message:"Could not check operational alerts.");}finally{lock.current=false;setBusy(false);}}
 useDashboardAutoLoad(load);
 return <main><p>BitcoinWalk / dashboard / alerts</p><h1>Alerts</h1><p>Checks imported image integrity and content-free replication state. Replication reports contain only city, destination and state counts—never event payloads, IDs, keys or private messages.</p><button disabled={busy} onClick={load}>{busy?"Checking…":"Check operational status"}</button><p role="status">{message}</p>{checkedAt&&<p>Last checked: {new Date(checkedAt).toLocaleString()}</p>}{replication&&<section><h2>Replication — {replication.state}</h2><p>Journal reconciliation: {replication.reconciled?"complete":"incomplete"}</p>{replication.cities.map(city=><article key={city.cityId}><h3>{city.state.toUpperCase()}</h3><p>City ID: {city.cityId}</p><p>Destination: {city.destination}</p><p>State counts: {Object.entries(city.counts).map(([state,count])=>`${state} ${count}`).join(", ")||"none"}</p></article>)}</section>}{alerts.map(alert=><article key={alert.id}><h2>{alert.status.toUpperCase()}</h2><p>City ID: {alert.cityId}</p><p>{alert.error}</p><p>Source: <a href={alert.sourceUrl} target="_blank" rel="noopener noreferrer">{alert.sourceUrl}</a></p>{alert.internalUrl&&<p>Stored asset: <a href={alert.internalUrl} target="_blank" rel="noopener noreferrer">open</a></p>}<p>Recorded: {new Date(alert.storedAt).toLocaleString()}</p></article>)}</main>;
}
