import {compareEvents,verifyEvent,type Event,type EventTemplate} from "nostr-tools";
import {DEFAULT_FEATURE_FLAGS,FEATURE_FLAGS_ID,FEATURE_FLAGS_KIND,featureFlagsSchema,type FeatureFlags,type FeatureFlagsInput} from "../domain/feature-flags";
import {isSuperAdmin,SUPER_ADMIN_PUBKEY} from "./authority";
import {queryRelayEvents} from "./city-records";
export type FeatureFlagRevision={event:Event;flags:FeatureFlags};
function one(event:Event,name:string){const tags=event.tags.filter(tag=>tag[0]===name&&tag.length===2);return tags.length===1?tags[0][1]:null;}
export function parseFeatureFlags(event:Event):FeatureFlagRevision|null{if(event.kind!==FEATURE_FLAGS_KIND||!verifyEvent(event)||!isSuperAdmin(event.pubkey))return null;try{const parsed=featureFlagsSchema.safeParse(JSON.parse(event.content));if(!parsed.success)return null;const flags=parsed.data,previous=event.tags.filter(tag=>tag[0]==="e"&&tag.length===4&&tag[2]===""&&tag[3]==="previous"),exact=event.tags.every(tag=>["d","i","client"].includes(tag[0])?tag.length===2:tag[0]==="e"&&tag.length===4&&tag[2]===""&&tag[3]==="previous");return exact&&one(event,"d")?.startsWith(`${FEATURE_FLAGS_ID}:`)&&one(event,"i")===FEATURE_FLAGS_ID&&one(event,"client")==="bitcoinwalk.org"&&previous.length===(flags.previousRevisionId?1:0)&&(!flags.previousRevisionId||previous[0][1]===flags.previousRevisionId)?{event,flags}:null;}catch{return null;}}
export function createFeatureFlagsRevision(flags:FeatureFlagsInput):EventTemplate{const value=featureFlagsSchema.parse(flags);return {kind:FEATURE_FLAGS_KIND,created_at:Math.floor(Date.now()/1000),content:JSON.stringify(value),tags:[["d",`${FEATURE_FLAGS_ID}:${crypto.randomUUID()}`],["i",FEATURE_FLAGS_ID],["client","bitcoinwalk.org"],...(value.previousRevisionId?[["e",value.previousRevisionId,"","previous"]]:[])]};}
export function latestFeatureFlags(rows:FeatureFlagRevision[]):FeatureFlagRevision|null{return [...rows].sort((a,b)=>compareEvents(a.event,b.event))[0]??null;}
export async function queryFeatureFlags(relays:string[]):Promise<FeatureFlagRevision[]>{const events=await queryRelayEvents(relays,[FEATURE_FLAGS_KIND],undefined,{authors:[SUPER_ADMIN_PUBKEY],limit:100});return events.map(parseFeatureFlags).filter((row):row is FeatureFlagRevision=>row!==null);}
export async function resolvedFeatureFlags(relays:string[]):Promise<FeatureFlags>{return latestFeatureFlags(await queryFeatureFlags(relays))?.flags??DEFAULT_FEATURE_FLAGS;}
