import {compareEvents,verifyEvent,type Event,type EventTemplate} from "nostr-tools";
import {SPONSORSHIP_ID,SPONSORSHIP_KIND,sponsorshipSchema,type Sponsorship,type SponsorshipInput,type SponsorshipPresentation} from "../domain/sponsorship";
import {isSuperAdmin,SUPER_ADMIN_PUBKEY} from "./authority";
import {queryRelayEvents} from "./city-records";

export type SponsorshipRevision={event:Event;sponsorship:Sponsorship};
function one(event:Event,name:string){const tags=event.tags.filter(tag=>tag[0]===name&&tag.length===2);return tags.length===1?tags[0][1]:null;}
export function sponsorshipKey(value:Sponsorship["scope"]){return value.type==="city"?`city:${value.cityId}`:`walk:${value.cityId}:${value.address}`;}
export function calendarAddress(event:Event):string|null{const values=event.tags.filter(tag=>tag[0]==="d"&&tag.length===2&&tag[1]);return values.length===1?values[0][1]:null;}
export function parseSponsorshipRevision(event:Event):SponsorshipRevision|null{
 if(event.kind!==SPONSORSHIP_KIND||!verifyEvent(event)||!isSuperAdmin(event.pubkey))return null;
 try{const parsed=sponsorshipSchema.safeParse(JSON.parse(event.content));if(!parsed.success)return null;const sponsorship=parsed.data,key=sponsorshipKey(sponsorship.scope),previous=event.tags.filter(tag=>tag[0]==="e"&&tag.length===4&&tag[2]===""&&tag[3]==="previous"),exact=event.tags.every(tag=>["d","i","scope","mode","client"].includes(tag[0])?tag.length===2:tag[0]==="e"&&tag.length===4&&tag[2]===""&&tag[3]==="previous");return exact&&one(event,"d")?.startsWith(`${SPONSORSHIP_ID}:${key}:`)&&one(event,"i")===SPONSORSHIP_ID&&one(event,"scope")===key&&one(event,"mode")===sponsorship.mode&&one(event,"client")==="bitcoinwalk.org"&&previous.length===(sponsorship.previousRevisionId?1:0)&&(!sponsorship.previousRevisionId||previous[0][1]===sponsorship.previousRevisionId)?{event,sponsorship}:null;}catch{return null;}
}
export function createSponsorshipRevision(input:SponsorshipInput):EventTemplate{const value=sponsorshipSchema.parse(input),key=sponsorshipKey(value.scope);return {kind:SPONSORSHIP_KIND,created_at:Math.floor(Date.now()/1000),content:JSON.stringify(value),tags:[["d",`${SPONSORSHIP_ID}:${key}:${crypto.randomUUID()}`],["i",SPONSORSHIP_ID],["scope",key],["mode",value.mode],["client","bitcoinwalk.org"],...(value.previousRevisionId?[["e",value.previousRevisionId,"","previous"]]:[])]};}
export function latestSponsorships(rows:SponsorshipRevision[]):SponsorshipRevision[]{const latest=new Map<string,SponsorshipRevision>();for(const row of [...rows].sort((a,b)=>compareEvents(a.event,b.event))){const key=sponsorshipKey(row.sponsorship.scope);if(!latest.has(key))latest.set(key,row);}return [...latest.values()];}
function presentation(row:SponsorshipRevision|undefined,now:number):SponsorshipPresentation|null{if(!row)return null;const value=row.sponsorship;if(value.startsAt!==undefined&&now<value.startsAt||value.endsAt!==undefined&&now>=value.endsAt)return {state:"empty"};if(value.mode==="hidden")return {state:"hidden"};if(value.mode==="empty")return {state:"empty"};if(value.mode==="sponsor")return {state:"sponsor",pubkey:value.sponsorPubkey!,...(value.website?{website:value.website}:{})};return null;}
export function resolveSponsorship(rows:SponsorshipRevision[],enabled:boolean,cityId:string,walkAddress?:string|null,now=Math.floor(Date.now()/1000)):SponsorshipPresentation{if(!enabled)return {state:"hidden"};const latest=latestSponsorships(rows),walk=walkAddress?latest.find(row=>sponsorshipKey(row.sponsorship.scope)===`walk:${cityId}:${walkAddress}`):undefined;if(walk&&walk.sponsorship.mode!=="inherit")return presentation(walk,now)!;const city=latest.find(row=>sponsorshipKey(row.sponsorship.scope)===`city:${cityId}`);return presentation(city,now)??{state:"hidden"};}
export async function querySponsorships(relays:string[]):Promise<SponsorshipRevision[]>{const events=await queryRelayEvents(relays,[SPONSORSHIP_KIND],undefined,{authors:[SUPER_ADMIN_PUBKEY],"#i":[SPONSORSHIP_ID],limit:500});return events.map(parseSponsorshipRevision).filter((row):row is SponsorshipRevision=>row!==null);}
