import {readFileSync} from "node:fs";
import {describe,expect,it} from "vitest";
const source=()=>readFileSync("src/app/admin/_approvals-screen.tsx","utf8");
describe("new-city approval readiness",()=>{
 it("runs and reports the compact post-approval activation checklist",()=>{const page=source();expect(page).toContain("completeCityActivation(signed)");expect(page).toContain("Activation checklist");expect(page).toContain("Generated automatically after approval");expect(page).toContain('paymentAuthorization:"Payment authorization"');expect(page).toContain('nip05:"NIP-05"');expect(page).toContain('lnurl:"Lightning address (LNURL)"');expect(page).not.toContain("prepareCityLogos(");});
 it("defaults the sponsor invitation on while allowing the administrator to deselect it",()=>{const page=source();expect(page).toContain("current[item.eventId]??true");expect(page).toContain('checked={inviteSponsors[submission.eventId]??true}');expect(page).toContain('className="inline-checkbox"');expect(page).toContain("Show sponsor invitation");expect(page).not.toContain("Show “Sponsor this BitcoinWalk”");});
 it("places the sponsor invitation on its own row while keeping the checkbox and label together",()=>{const styles=readFileSync("src/app/styles.css","utf8");expect(styles).toContain(".inline-checkbox { display: flex; width: fit-content; align-items: center;");expect(styles).not.toContain(".inline-checkbox { display: inline-flex;");});
 it("publishes an empty city sponsorship before the final approval without replacing an assigned sponsor",()=>{const page=source();expect(page).toContain('const desired=invite?"empty" as const:"hidden" as const');expect(page).toContain('mode:desired,...(existing?{previousRevisionId:existing.event.id}:{})');expect(page).toContain('["empty","hidden"].includes(existing.sponsorship.mode)');expect(page).toContain("Existing ${existing.sponsorship.mode} sponsorship setting preserved.");expect(page).toContain("Final step: sign the city decision");});
 it("compresses technical content under one review disclosure and short actions",()=>{const page=source();expect(page).toContain("Review request and approval settings");expect(page).toContain('?"Approved":"Approve"');expect(page).toContain('>Reject</button>');expect(page).not.toContain("Review submitted details and technical records");});
 it("renders submitted city values as one compact list instead of per-field cards",()=>{const page=source();expect(page).toContain("<SubmittedCityFields submission={submission}/>");expect(page).toContain("<ul>");expect(page).toContain("<strong>{change.label}:</strong>");expect(page).not.toContain('className="revision-change"');expect(page).not.toContain("Previous signed value");});
 it("lets the super-admin override alternative names below the URL and keeps city imagery outside the disclosure",()=>{const page=source(),url=page.indexOf("Public URL"),aliases=page.indexOf("Alternative city names",url),detailsEnd=page.indexOf("</details>",aliases),image=page.indexOf("<section><h3>City image",detailsEnd);expect(url).toBeGreaterThan(-1);expect(aliases).toBeGreaterThan(url);expect(detailsEnd).toBeGreaterThan(aliases);expect(image).toBeGreaterThan(detailsEnd);expect(page).toContain("aliases:approvedAliases");expect(page).toContain("setAliases(current=>Object.fromEntries");});
});
