#!/usr/bin/env bash
set -euo pipefail
[[ ( $# -eq 2 && "$1" == *.tar.zst.gpg && "$2" == worker ) || ( $# -eq 3 && "$1" == *.tar.zst.gpg && "$2" == signer && "$3" =~ ^[0-9a-f]{64}$ ) ]]||{ echo "usage: $0 BACKUP.tar.zst.gpg worker | $0 BACKUP.tar.zst.gpg signer EXPECTED_PROVIDER_PUBKEY" >&2;exit 64; }
ciphertext="$(realpath "$1")";component="$2";expected_pubkey="${3:-}";work="$(mktemp -d)";archive="$work/archive.tar.zst";tarball="$work/archive.tar";trap 'rm -rf -- "$work"' EXIT;chmod 700 "$work";gpg_bin="${BITCOINWALK_RESTORE_GPG:-gpg}";verify="${BITCOINWALK_RECEIPT_RESTORE_VERIFY:-$(cd "$(dirname "${BASH_SOURCE[0]}")"&&pwd)/verify-rustress-receipt-restore.cjs}"
max_expanded_bytes="${BITCOINWALK_RECEIPT_RESTORE_MAX_EXPANDED_BYTES:-536870912}";[[ "$max_expanded_bytes" =~ ^[0-9]+$ && "$max_expanded_bytes" -ge 1048576 && "$max_expanded_bytes" -le 536870912 ]]||{ echo "Invalid expanded backup limit" >&2;exit 64; };max_expanded_blocks=$(( (max_expanded_bytes + 511) / 512 ))
"$gpg_bin" --output "$archive" --decrypt "$ciphertext";if ! (ulimit -f "$max_expanded_blocks";exec timeout --signal=KILL 120 zstd -q -d -M128MB -c -- "$archive">"$tarball");then echo "Receipt backup exceeds the expanded-size limit or could not be decompressed" >&2;exit 1;fi
[[ "$(stat -c '%s' "$tarball")" -le "$max_expanded_bytes" ]]||{ echo "Receipt backup exceeds the expanded-size limit" >&2;exit 1; };mapfile -t entries < <(tar -tf "$tarball");mapfile -t types < <(tar --numeric-owner -tvf "$tarball"|awk '{print substr($1,1,1)}');mapfile -t sizes < <(tar --numeric-owner -tvf "$tarball"|awk '{print $3}');expected=2;[[ "$component" == signer ]]&&expected=4;[[ "${#entries[@]}" -eq "$expected" && "${#types[@]}" -eq "$expected" && "${#sizes[@]}" -eq "$expected" ]]||exit 1
for type in "${types[@]}";do [[ "$type" == - ]]||exit 1;done
total_size=0;for size in "${sizes[@]}";do [[ "$size" =~ ^[0-9]+$ && "${#size}" -le 9 ]]||exit 1;(( size <= max_expanded_bytes - total_size ))||{ echo "Receipt backup members exceed the expanded-size limit" >&2;exit 1; };total_size=$((total_size + size));done
allowed='^(database.sqlite|manifest.txt)$';[[ "$component" == signer ]]&&allowed='^(database.sqlite|manifest.txt|provider-secret-key|provider-pubkey)$';for entry in "${entries[@]}";do [[ "$entry" =~ $allowed ]]||exit 1;done
tar --no-same-owner --no-same-permissions -xf "$tarball" -C "$work";for entry in "${entries[@]}";do [[ -f "$work/$entry" && ! -L "$work/$entry" ]]||exit 1;done
verify_args=("$component" "$work");[[ "$component" == signer ]]&&verify_args+=("$expected_pubkey");node "$verify" "${verify_args[@]}"|grep -qx "RECEIPT_RESTORE_MATERIAL_OK component=$component"
printf 'RECEIPT_RESTORE_REHEARSAL_OK component=%s decrypted_material_removed_on_exit=yes\n' "$component"
