"use client";
import {nip19,type Event} from "nostr-tools";
import {useCallback,useRef,useState} from "react";
import {directoryRequestTemplate,type DirectoryRequestCommand} from "../directory/request-auth";
import type {DirectorySigningRequest} from "../directory/request-store";
import {SUPER_ADMIN_PUBKEY} from "../nostr/authority";
import {createCityDirectoryRoot,verifySignedCityDirectoryTemplate} from "../nostr/city-directory";
import {signForOrganizer} from "../nostr/organizer-identity";
import {getBrowserExtensionPubkey,signWithBrowserExtension} from "../nostr/signer";
import {useDashboard,useDashboardAutoLoad} from "./dashboard-context";

async function request(command:DirectoryRequestCommand,actor:string){
 const authorization=await signForOrganizer(directoryRequestTemplate(command,window.location.origin),actor);
 const response=await fetch("/api/directory-requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({event:authorization}),cache:"no-store",signal:AbortSignal.timeout(60000)});
 const result=await response.json();if(!response.ok)throw new Error(result.error??"Directory request unavailable.");return result as {request?:DirectorySigningRequest;requests?:DirectorySigningRequest[]};
}
function recoveryKey(value:string){const decoded=nip19.decode(value.trim());if(decoded.type!=="npub"||typeof decoded.data!=="string")throw new Error("Use the npub of a separate offline recovery identity. Never enter an nsec.");return decoded.data;}
const label:Record<DirectorySigningRequest["status"],string>={"awaiting-owner":"Awaiting owner signature",signed:"Signed — ready for activation",rejected:"Rejected by owner",superseded:"Superseded",expired:"Expired"};

export default function CityDirectoryRequests(){
 const session=useDashboard(),lock=useRef(false),[rows,setRows]=useState<DirectorySigningRequest[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("Loading directory requests…"),[cityId,setCityId]=useState(""),[primary,setPrimary]=useState(""),[mirrors,setMirrors]=useState(""),[recoveries,setRecoveries]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{if(lock.current||!session.pubkey)return;lock.current=true;setBusy(true);try{const result=await request({action:"list"},session.pubkey);setRows(result.requests??[]);setMessage(result.requests?.length?"Directory requests loaded.":session.role==="super-admin"?"No directory requests yet. Prepare the London request below.":"No directory request is waiting for this identity.");}catch(error){setMessage(error instanceof Error?error.message:"Could not load directory requests.");}finally{lock.current=false;setBusy(false);}},[session.pubkey,session.role]);
 useDashboardAutoLoad(load);
 async function prepare(){if(lock.current||session.role!=="super-admin"||!cityId)return;lock.current=true;setBusy(true);try{const result=await request({action:"prepare",cityId,primaryRelay:primary,mirrorRelays:mirrors.split(/[\n,]/).map(v=>v.trim()).filter(Boolean),operatorPubkeys:[SUPER_ADMIN_PUBKEY]},session.pubkey);setRows(current=>[result.request!,...current]);setMessage("Immutable request prepared. The owner can now review it and add only the offline recovery npub before signing.");}catch(error){setMessage(error instanceof Error?error.message:"Could not prepare request.");}finally{lock.current=false;setBusy(false);}}
 async function sign(row:DirectorySigningRequest){if(lock.current)return;lock.current=true;setBusy(true);try{const identity=await getBrowserExtensionPubkey();if(identity!==row.ownerPubkey)throw new Error("Connect the verified city-owner identity shown in this request.");const recoveryNpub=(recoveries[row.id]??"").trim(),recoveryPubkey=recoveryKey(recoveryNpub);const template=createCityDirectoryRoot({cityId:row.cityId,ownerPubkey:row.ownerPubkey,operatorPubkeys:row.operatorPubkeys,recoveryPubkey,primaryRelay:row.primaryRelay,mirrorRelays:row.mirrorRelays},row.eventCreatedAt);if(!window.confirm(`Sign the permanent directory root for ${row.cityName}?\n\nPrimary: ${row.primaryRelay}\nOperator: ${row.operatorPubkeys.join(", ")}\nRecovery: ${recoveryNpub}\n\nNothing will be published yet.`))throw new Error("Signing cancelled.");const event=verifySignedCityDirectoryTemplate(await signWithBrowserExtension(template),template,identity);const result=await request({action:"sign",requestId:row.id,recoveryNpub,event},identity);setRows(current=>current.map(item=>item.id===row.id?result.request!:item));setMessage(`Signed event ${event.id} saved without publication. Super-admin activation is a separate reviewed step.`);}catch(error){setMessage(error instanceof Error?error.message:"Could not sign request.");}finally{lock.current=false;setBusy(false);}}
 async function transition(row:DirectorySigningRequest,action:"reject"|"supersede"){if(lock.current)return;lock.current=true;setBusy(true);try{const result=await request({action,requestId:row.id},session.pubkey);setRows(current=>current.map(item=>item.id===row.id?result.request!:item));setMessage(action==="reject"?"Request rejected. Nothing was signed or published.":"Request superseded. Prepare a replacement only after reviewing the changed fields.");}catch(error){setMessage(error instanceof Error?error.message:"Could not update request.");}finally{lock.current=false;setBusy(false);}}
 const active=rows.filter(row=>!["superseded","expired"].includes(row.status));
 return <main><h1>City relay setup</h1><p>Prepare and sign a portable city-directory record with the connected Nostr signer. BitcoinWalk never receives the private key.</p><p>Signing does not publish or activate the relay, and it does not itself establish BitcoinWalk recognition or payment entitlement. Activation remains a separate super-admin review.</p><p role="status" aria-live="polite">{message}</p><button type="button" disabled={busy} onClick={()=>void load()}>{busy?"Working…":"Refresh"}</button>
  {session.role==="super-admin"&&<section><h2>Prepare owner request</h2><label>Approved city <select value={cityId} onChange={event=>{const id=event.target.value;setCityId(id);const city=session.cities.find(item=>item.id===id);setPrimary(city?`wss://${city.name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}.bitcoinwalk.org/`:"");}}><option value="">Choose city…</option>{session.cities.map(city=><option key={city.id} value={city.id}>{city.name}</option>)}</select></label><label>Primary city relay <input type="url" value={primary} onChange={event=>setPrimary(event.target.value)} placeholder="wss://london.bitcoinwalk.org/"/></label><label>Optional mirror relays <textarea value={mirrors} onChange={event=>setMirrors(event.target.value)} placeholder="One WSS root URL per line"/></label><p>The BitcoinWalk super-admin is listed visibly as an endpoint-only operator. It cannot rotate ownership or replace recovery authority.</p><button type="button" disabled={busy||!cityId||!primary} onClick={()=>void prepare()}>Prepare immutable request</button></section>}
  <section><h2>{session.role==="super-admin"?"Directory requests":"Requests for your cities"}</h2>{!active.length?<p>No active requests.</p>:active.map(row=><article key={row.id}><h3>{row.cityName}</h3><p><strong>{label[row.status]}</strong> · expires {new Date(row.expiresAt*1000).toLocaleString()}</p><dl><dt>City ID</dt><dd><code>{row.cityId}</code></dd><dt>Verified owner</dt><dd><code>{row.ownerPubkey}</code></dd><dt>Primary relay</dt><dd><code>{row.primaryRelay}</code></dd><dt>Mirrors</dt><dd>{row.mirrorRelays.length?row.mirrorRelays.map(url=><code key={url}>{url} </code>):"None"}</dd><dt>Endpoint-only operators</dt><dd>{row.operatorPubkeys.map(key=><code key={key}>{key} </code>)}</dd></dl>{row.status==="awaiting-owner"&&session.pubkey===row.ownerPubkey&&<><label>Offline recovery npub <input value={recoveries[row.id]??""} onChange={event=>setRecoveries(current=>({...current,[row.id]:event.target.value}))} placeholder="npub1…" autoComplete="off" spellCheck={false}/></label><p>Use a separate key kept offline. Never paste an nsec. It must differ from the owner and operator identities.</p><button disabled={busy||!(recoveries[row.id]??"").trim()} onClick={()=>void sign(row)}>Review and sign exact root</button>{" "}<button disabled={busy} onClick={()=>void transition(row,"reject")}>Reject request</button></>}{row.status==="signed"&&<p>Event ID: <code>{row.signedEvent?.id}</code><br/>Recovery: <code>{row.recoveryPubkey}</code></p>}{session.role==="super-admin"&&(row.status==="awaiting-owner"||row.status==="signed")&&<button disabled={busy} onClick={()=>void transition(row,"supersede")}>Supersede request</button>}</article>)}</section>
 </main>;
}
