"use client";

import Image from "next/image";
import {useRef, useState} from "react";
import {nip19, type EventTemplate} from "nostr-tools";
import {isSuperAdmin} from "../nostr/authority";
import {authorizeProSetup, proSetupTemplate} from "../nostr/pro-setup-command";
import {signWithBrowserExtension} from "../nostr/signer";

type ReviewRow={requestId:string;cityId:string;expiresAt:number;brandPubkey:string;proofsReady:boolean;profile:{revisionId:string;artworkVersion:number;signerVersion:number;payoutVersion:number;name:string;picture:string;banner:string;website:string}};
export default function CityBrandReview({actor}:{actor:string}){
 const lock=useRef(false),[busy,setBusy]=useState(false),[rows,setRows]=useState<ReviewRow[]>([]),[message,setMessage]=useState("Load privately signed city-account requests. Nothing is published from this screen.");
 async function signedRequest(command:Parameters<typeof proSetupTemplate>[0],extra:Record<string,unknown>={}){const origin=window.location.origin,event=await signWithBrowserExtension(proSetupTemplate(command,origin));if(event.pubkey!==actor||!isSuperAdmin(event.pubkey)||JSON.stringify(authorizeProSetup(event,origin))!==JSON.stringify(command))throw new Error("Connect the BitcoinWalk super-admin identity.");const response=await fetch("/api/pro-setup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({event,...extra}),signal:AbortSignal.timeout(60_000)}),body=await response.json();if(!response.ok)throw new Error(body.error||"City account review failed.");return body;}
 async function run(work:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setMessage("");try{await work();}catch(error){setMessage(error instanceof Error?error.message:"City account review failed.");}finally{lock.current=false;setBusy(false);}}
 function load(){void run(async()=>{const body=await signedRequest({action:"list-brand-requests"});setRows(body.requests);setMessage(`${body.requests.length} private activation request(s).`);});}
 function approve(row:ReviewRow){void run(async()=>{if(!row.proofsReady)throw new Error("Both organizer and city signer proofs are required.");const reviewed=await signedRequest({action:"review-brand-request",requestId:row.requestId}),template=reviewed.template as EventTemplate;if(!window.confirm(`Attest that this is the official BitcoinWalk identity for ${row.profile.name}?\n\nCity identity: ${nip19.npubEncode(row.brandPubkey)}\nArtwork revision: ${row.profile.revisionId}\n\nThe name and artwork were generated automatically from the approved city. This stores the exact official-identity binding privately; it does not publish or activate it.`))throw new Error("Review cancelled.");const approvalEvent=await signWithBrowserExtension(template);if(approvalEvent.pubkey!==actor)throw new Error("Super-admin identity changed while signing.");const body=await signedRequest({action:"approve-brand-request",requestId:row.requestId},{approvalEvent});setRows(current=>current.filter(item=>item.requestId!==row.requestId));setMessage(body.request.message);});}
 return <section><h1>City account review</h1><p>The city name, avatar and banner are generated automatically from the approved city record. Your signature does not edit those fields; it attests that the reviewed city npub is BitcoinWalk&apos;s official identity for this city. Approval remains private until relay admission and read-back are implemented.</p><button type="button" disabled={busy} onClick={load}>{busy?"Working…":"Load activation requests"}</button>{message&&<p role="status">{message}</p>}{rows.map(row=><article key={row.requestId}><h2>{row.profile.name}</h2><Image unoptimized src={row.profile.banner} alt="Proposed city profile banner" width={750} height={250} style={{width:"100%",maxWidth:750,height:"auto"}}/><p><Image unoptimized src={row.profile.picture} alt="Proposed city avatar" width={96} height={96} style={{borderRadius:"50%"}}/></p><p>City identity: <code title={nip19.npubEncode(row.brandPubkey)}>{nip19.npubEncode(row.brandPubkey).slice(0,12)}…{nip19.npubEncode(row.brandPubkey).slice(-8)}</code><br/>Artwork revision: <code>{row.profile.revisionId.slice(0,8)}…{row.profile.revisionId.slice(-8)}</code> · artwork v{row.profile.artworkVersion} · signer v{row.profile.signerVersion} · payout v{row.profile.payoutVersion}<br/>Website: <a href={row.profile.website}>{row.profile.website}</a><br/>Proofs: <strong>{row.proofsReady?"ready":"missing"}</strong><br/>Expires: {new Date(row.expiresAt*1000).toLocaleString()}</p><button type="button" disabled={busy||!row.proofsReady} onClick={()=>approve(row)}>Attest official city identity</button></article>)}</section>;
}
