"use client";

import {nip19,type Event} from "nostr-tools";
import {useCallback,useRef,useState} from "react";
import {directoryRequestTemplate,type DirectoryRequestCommand} from "../directory/request-auth";
import type {DirectorySigningRequest} from "../directory/request-store";
import {directorySuccessorRequestTemplate,type DirectorySuccessorRequestCommand} from "../directory/successor-request-auth";
import type {DirectorySuccessorRequest} from "../directory/successor-request-store";
import {SUPER_ADMIN_PUBKEY} from "../nostr/authority";
import {createCityDirectoryRoot,verifySignedCityDirectorySuccessor,verifySignedCityDirectoryTemplate} from "../nostr/city-directory";
import {signForOrganizer} from "../nostr/organizer-identity";
import {getBrowserExtensionPubkey,signWithBrowserExtension} from "../nostr/signer";
import {useDashboard,useDashboardAutoLoad} from "./dashboard-context";

async function post<T>(path:string,event:Event){
 const response=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({event}),cache:"no-store",signal:AbortSignal.timeout(60000)});
 const result=await response.json();if(!response.ok)throw new Error(result.error??"Directory request unavailable.");return result as T;
}
async function rootRequest(command:DirectoryRequestCommand,actor:string){
 const authorization=await signForOrganizer(directoryRequestTemplate(command,window.location.origin),actor);
 return post<{request?:DirectorySigningRequest;requests?:DirectorySigningRequest[]}>("/api/directory-requests",authorization);
}
async function successorRequest(command:DirectorySuccessorRequestCommand,actor:string){
 const authorization=await signForOrganizer(directorySuccessorRequestTemplate(command,window.location.origin),actor);
 return post<{request?:DirectorySuccessorRequest;requests?:DirectorySuccessorRequest[]}>("/api/directory-successor-requests",authorization);
}
function recoveryKey(value:string){const decoded=nip19.decode(value.trim());if(decoded.type!=="npub"||typeof decoded.data!=="string")throw new Error("Use the npub of a separate offline recovery identity. Never enter an nsec.");return decoded.data;}
const rootLabel:Record<DirectorySigningRequest["status"],string>={"awaiting-owner":"Awaiting owner signature",signed:"Signed — ready for activation",rejected:"Rejected by owner",superseded:"Superseded",expired:"Expired"};
const successorLabel:Record<DirectorySuccessorRequest["status"],string>={"awaiting-owner":"Awaiting owner signature",signed:"Signed rehearsal — not published",rejected:"Rejected by owner",superseded:"Superseded",expired:"Expired"};

export default function CityDirectoryRequests(){
 const session=useDashboard(),lock=useRef(false),[roots,setRoots]=useState<DirectorySigningRequest[]>([]),[successors,setSuccessors]=useState<DirectorySuccessorRequest[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("Loading directory requests…"),[cityId,setCityId]=useState(""),[successorCityId,setSuccessorCityId]=useState(""),[primary,setPrimary]=useState(""),[mirrors,setMirrors]=useState(""),[recoveries,setRecoveries]=useState<Record<string,string>>({}),[focusRequest,setFocusRequest]=useState("");
 const load=useCallback(async()=>{if(lock.current||!session.pubkey)return;lock.current=true;setBusy(true);try{
  const linkedRequest=new URLSearchParams(window.location.search).get("request")??"";setFocusRequest(linkedRequest);
  const rootResult=linkedRequest?{requests:[] as DirectorySigningRequest[]}:await rootRequest({action:"list"},session.pubkey);
  const successorResult=await successorRequest({action:"list"},session.pubkey);
  setRoots(rootResult.requests??[]);setSuccessors(successorResult.requests??[]);
  const count=(rootResult.requests?.length??0)+(successorResult.requests?.length??0);
  setMessage(count?"Directory requests loaded.":session.role==="super-admin"?"No directory requests yet.":"No directory request is waiting for this identity.");
 }catch(error){setMessage(error instanceof Error?error.message:"Could not load directory requests.");}finally{lock.current=false;setBusy(false);}},[session.pubkey,session.role]);
 useDashboardAutoLoad(load);
 async function prepareRoot(){if(lock.current||session.role!=="super-admin"||!cityId)return;lock.current=true;setBusy(true);try{const result=await rootRequest({action:"prepare",cityId,primaryRelay:primary,mirrorRelays:mirrors.split(/[\n,]/).map(v=>v.trim()).filter(Boolean),operatorPubkeys:[SUPER_ADMIN_PUBKEY]},session.pubkey);setRoots(current=>[result.request!,...current]);setMessage("Immutable root request prepared. The owner can now review it and add only the offline recovery npub before signing.");}catch(error){setMessage(error instanceof Error?error.message:"Could not prepare request.");}finally{lock.current=false;setBusy(false);}}
 async function prepareSuccessor(){if(lock.current||session.role!=="super-admin"||!successorCityId)return;lock.current=true;setBusy(true);try{const result=await successorRequest({action:"prepare",cityId:successorCityId},session.pubkey),request=result.request!;setSuccessors(current=>[request,...current]);setFocusRequest(request.id);window.history.replaceState(null,"",`/admin/directory?request=${request.id}`);setMessage("Owner-bound successor rehearsal prepared. Copy its link below; signing will store the exact event without publishing it.");}catch(error){setMessage(error instanceof Error?error.message:"Could not prepare successor rehearsal.");}finally{lock.current=false;setBusy(false);}}
 async function signRoot(row:DirectorySigningRequest){if(lock.current)return;lock.current=true;setBusy(true);try{const identity=await getBrowserExtensionPubkey();if(identity!==row.ownerPubkey)throw new Error("Connect the verified city-owner identity shown in this request.");const recoveryNpub=(recoveries[row.id]??"").trim(),recoveryPubkey=recoveryKey(recoveryNpub);const template=createCityDirectoryRoot({cityId:row.cityId,ownerPubkey:row.ownerPubkey,operatorPubkeys:row.operatorPubkeys,recoveryPubkey,primaryRelay:row.primaryRelay,mirrorRelays:row.mirrorRelays},row.eventCreatedAt);if(!window.confirm(`Sign the permanent directory root for ${row.cityName}?\n\nPrimary: ${row.primaryRelay}\nOperator: ${row.operatorPubkeys.join(", ")}\nRecovery: ${recoveryNpub}\n\nNothing will be published yet.`))throw new Error("Signing cancelled.");const event=verifySignedCityDirectoryTemplate(await signWithBrowserExtension(template),template,identity);const result=await rootRequest({action:"sign",requestId:row.id,recoveryNpub,event},identity);setRoots(current=>current.map(item=>item.id===row.id?result.request!:item));setMessage(`Signed event ${event.id} saved without publication. Super-admin activation is a separate reviewed step.`);}catch(error){setMessage(error instanceof Error?error.message:"Could not sign request.");}finally{lock.current=false;setBusy(false);}}
 async function signSuccessor(row:DirectorySuccessorRequest){if(lock.current)return;lock.current=true;setBusy(true);try{const identity=await getBrowserExtensionPubkey();if(identity!==row.ownerPubkey)throw new Error("Connect the verified current city-owner identity shown in this request.");if(!window.confirm(`Sign the BW-95 rehearsal successor for ${row.cityName}?\n\nPredecessor: ${row.predecessorEvent.id}\nPrimary and authorities remain unchanged.\n\nThe signed event will be stored for validation and will not be published.`))throw new Error("Signing cancelled.");setMessage("Approve the exact kind 30309 successor in your connected signer…");const event=verifySignedCityDirectorySuccessor(await signWithBrowserExtension(row.template),row.template,identity);const result=await successorRequest({action:"sign",requestId:row.id,event},identity);setSuccessors(current=>current.map(item=>item.id===row.id?result.request!:item));setMessage(`Successor ${event.id} classified and saved without publication. The live London directory remains unchanged.`);}catch(error){setMessage(error instanceof Error?error.message:"Could not sign successor rehearsal.");}finally{lock.current=false;setBusy(false);}}
 async function transitionRoot(row:DirectorySigningRequest,action:"reject"|"supersede"){if(lock.current)return;lock.current=true;setBusy(true);try{const result=await rootRequest({action,requestId:row.id},session.pubkey);setRoots(current=>current.map(item=>item.id===row.id?result.request!:item));setMessage(action==="reject"?"Request rejected. Nothing was signed or published.":"Request superseded.");}catch(error){setMessage(error instanceof Error?error.message:"Could not update request.");}finally{lock.current=false;setBusy(false);}}
 async function transitionSuccessor(row:DirectorySuccessorRequest,action:"reject"|"supersede"){if(lock.current)return;lock.current=true;setBusy(true);try{const result=await successorRequest({action,requestId:row.id},session.pubkey);setSuccessors(current=>current.map(item=>item.id===row.id?result.request!:item));setMessage(action==="reject"?"Successor rehearsal rejected. Nothing was published.":"Successor rehearsal superseded. Its evidence was retained and nothing was published.");}catch(error){setMessage(error instanceof Error?error.message:"Could not update successor request.");}finally{lock.current=false;setBusy(false);}}
 async function copyLink(id:string){const link=`${window.location.origin}/admin/directory?request=${id}`;await navigator.clipboard.writeText(link);setMessage("Owner request link copied. The URL grants no authority; the verified owner identity is still required.");}
 const activeRoots=roots.filter(row=>!["superseded","expired"].includes(row.status));
 const activeSuccessors=successors.filter(row=>!["superseded","expired"].includes(row.status)&&(!focusRequest||row.id===focusRequest));
 return <main><h1>City relay setup</h1><p>Prepare and sign portable city-directory records with the connected Nostr signer. BitcoinWalk never receives the private key.</p><p>Signing does not publish or activate the relay, and it does not itself establish BitcoinWalk recognition or payment entitlement. Activation remains a separate super-admin review.</p><p role="status" aria-live="polite">{message}</p><button type="button" disabled={busy} onClick={()=>void load()}>{busy?"Working…":"Refresh"}</button>
  {session.role==="super-admin"&&<><section><h2>Prepare owner root request</h2><label>Approved city <select value={cityId} onChange={event=>{const id=event.target.value;setCityId(id);const city=session.cities.find(item=>item.id===id);setPrimary(city?`wss://${city.name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}.bitcoinwalk.org/`:"");}}><option value="">Choose city…</option>{session.cities.map(city=><option key={city.id} value={city.id}>{city.name}</option>)}</select></label><label>Primary city relay <input type="url" value={primary} onChange={event=>setPrimary(event.target.value)} placeholder="wss://london.bitcoinwalk.org/"/></label><label>Optional mirror relays <textarea value={mirrors} onChange={event=>setMirrors(event.target.value)} placeholder="One WSS root URL per line"/></label><p>The BitcoinWalk super-admin is listed visibly as an endpoint-only operator. It cannot rotate ownership or replace recovery authority.</p><button type="button" disabled={busy||!cityId||!primary} onClick={()=>void prepareRoot()}>Prepare immutable request</button></section>
  <section><h2>Prepare successor rehearsal</h2><p>Create an owner-signed successor candidate from the exact anchored state. Endpoints and authorities remain unchanged; the candidate is stored for BW-95 validation and is never published by this workflow.</p><label>Anchored city <select value={successorCityId} onChange={event=>setSuccessorCityId(event.target.value)}><option value="">Choose city…</option>{session.cities.map(city=><option key={city.id} value={city.id}>{city.name}</option>)}</select></label><button type="button" disabled={busy||!successorCityId} onClick={()=>void prepareSuccessor()}>Prepare rehearsal and owner link</button></section></>}
  <section><h2>{session.role==="super-admin"?"Root requests":"Requests for your cities"}</h2>{!activeRoots.length?<p>No active root requests.</p>:activeRoots.map(row=><article key={row.id}><h3>{row.cityName}</h3><p><strong>{rootLabel[row.status]}</strong> · expires {new Date(row.expiresAt*1000).toLocaleString()}</p><dl><dt>City ID</dt><dd><code>{row.cityId}</code></dd><dt>Verified owner</dt><dd><code>{nip19.npubEncode(row.ownerPubkey)}</code></dd><dt>Primary relay</dt><dd><code>{row.primaryRelay}</code></dd><dt>Mirrors</dt><dd>{row.mirrorRelays.length?row.mirrorRelays.map(url=><code key={url}>{url} </code>):"None"}</dd><dt>Endpoint-only operators</dt><dd>{row.operatorPubkeys.map(key=><code key={key}>{key} </code>)}</dd></dl>{row.status==="awaiting-owner"&&session.pubkey===row.ownerPubkey&&<><label>Offline recovery npub <input value={recoveries[row.id]??""} onChange={event=>setRecoveries(current=>({...current,[row.id]:event.target.value}))} placeholder="npub1…" autoComplete="off" spellCheck={false}/></label><p>Use a separate key kept offline. Never paste an nsec. It must differ from the owner and operator identities.</p><button disabled={busy||!(recoveries[row.id]??"").trim()} onClick={()=>void signRoot(row)}>Review and sign exact root</button>{" "}<button disabled={busy} onClick={()=>void transitionRoot(row,"reject")}>Reject request</button></>}{row.status==="signed"&&<p>Event ID: <code>{row.signedEvent?.id}</code><br/>Recovery: <code>{row.recoveryPubkey}</code></p>}{session.role==="super-admin"&&(row.status==="awaiting-owner"||row.status==="signed")&&<button disabled={busy} onClick={()=>void transitionRoot(row,"supersede")}>Supersede request</button>}</article>)}</section>
  <section><h2>Successor rehearsals</h2>{focusRequest&&!activeSuccessors.length?<p>No owner-authorized active request matches this link.</p>:!activeSuccessors.length?<p>No active successor rehearsals.</p>:activeSuccessors.map(row=><article key={row.id}><h3>{row.cityName}</h3><p><strong>{successorLabel[row.status]}</strong> · expires {new Date(row.expiresAt*1000).toLocaleString()}</p><p><strong>Rehearsal only:</strong> signing stores the candidate for validation. It does not publish or activate it.</p><dl><dt>Verified owner</dt><dd><code>{nip19.npubEncode(row.ownerPubkey)}</code></dd><dt>Anchored root</dt><dd><code>{row.rootEventId}</code></dd><dt>Exact predecessor</dt><dd><code>{row.predecessorEvent.id}</code></dd><dt>Classification</dt><dd>Owner update · endpoints and authorities unchanged</dd></dl>{session.role==="super-admin"&&<p><button type="button" onClick={()=>void copyLink(row.id)}>Copy owner request link</button></p>}{row.status==="awaiting-owner"&&session.pubkey===row.ownerPubkey&&<><button disabled={busy} onClick={()=>void signSuccessor(row)}>Review and sign rehearsal successor</button>{" "}<button disabled={busy} onClick={()=>void transitionSuccessor(row,"reject")}>Reject request</button></>}{row.status==="signed"&&<p>Signed event: <code>{row.signedEvent?.id}</code><br/>Stored classification: <code>{row.classification}</code></p>}{session.role==="super-admin"&&(row.status==="awaiting-owner"||row.status==="signed")&&<button disabled={busy} onClick={()=>void transitionSuccessor(row,"supersede")}>Supersede rehearsal</button>}</article>)}</section>
 </main>;
}
