"use client";

import Image from "next/image";
import {useRef, useState} from "react";
import {nip19, type EventTemplate} from "nostr-tools";
import {isSuperAdmin} from "../nostr/authority";
import {authorizeProSetup, proSetupTemplate} from "../nostr/pro-setup-command";
import {authenticateWithBrowserExtension,signWithBrowserExtension} from "../nostr/signer";
import {publishVerifiedEvent} from "../nostr/relay";
import {relayConfig} from "../lib/relay-config";
import {useDashboardAutoLoad} from "./dashboard-context";
import {announcePendingRequestCount} from "./pending-request-count";

type ReviewRow={requestId:string;cityId:string;expiresAt:number;brandPubkey:string;proofsReady:boolean;state:"pending"|"approved"|"active";profile:{revisionId:string;artworkVersion:number;signerVersion:number;payoutVersion:number;name:string;picture:string;banner:string;website:string}};
export default function CityBrandReview({actor}:{actor:string}){
 const lock=useRef(false),[busy,setBusy]=useState(false),[rows,setRows]=useState<ReviewRow[]>([]),[message,setMessage]=useState("Load privately signed city-account requests. Publication is always a separate, explicit action.");
 async function signedRequest(command:Parameters<typeof proSetupTemplate>[0],extra:Record<string,unknown>={}){const origin=window.location.origin,event=await signWithBrowserExtension(proSetupTemplate(command,origin));if(event.pubkey!==actor||!isSuperAdmin(event.pubkey)||JSON.stringify(authorizeProSetup(event,origin))!==JSON.stringify(command))throw new Error("Connect the BitcoinWalk super-admin identity.");const response=await fetch("/api/pro-setup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({event,...extra}),signal:AbortSignal.timeout(60_000)}),body=await response.json();if(!response.ok)throw new Error(body.error||"City account review failed.");return body;}
 async function run(work:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setMessage("");try{await work();}catch(error){setMessage(error instanceof Error?error.message:"City account review failed.");}finally{lock.current=false;setBusy(false);}}
 async function load(){await run(async()=>{const body=await signedRequest({action:"list-brand-requests"}),requests=body.requests as ReviewRow[],open=requests.filter(row=>row.state!=="active");setRows(requests);announcePendingRequestCount(open.length,"pro-activations");setMessage(`${open.length} activation request(s) need attention.`);});}
 useDashboardAutoLoad(load);
 function approve(row:ReviewRow){void run(async()=>{if(!row.proofsReady)throw new Error("Both organizer and city signer proofs are required.");const reviewed=await signedRequest({action:"review-brand-request",requestId:row.requestId}),template=reviewed.template as EventTemplate;if(!window.confirm(`Attest that this is the official BitcoinWalk identity for ${row.profile.name}?\n\nCity identity: ${nip19.npubEncode(row.brandPubkey)}\nArtwork revision: ${row.profile.revisionId}\n\nThe name and artwork were generated automatically from the approved city. This stores the exact official-identity binding privately; it does not publish or activate it.`))throw new Error("Review cancelled.");const approvalEvent=await signWithBrowserExtension(template);if(approvalEvent.pubkey!==actor)throw new Error("Super-admin identity changed while signing.");const body=await signedRequest({action:"approve-brand-request",requestId:row.requestId},{approvalEvent});setRows(current=>current.map(item=>item.requestId===row.requestId?{...item,state:"approved"}:item));setMessage(`${body.request.message} Publish and verify it below when ready.`);});}
 function publish(row:ReviewRow){void run(async()=>{if(!window.confirm(`Publish the exact approved official identity for ${row.profile.name}?\n\nThe app will recheck authority and setup, publish the existing signature unchanged, then independently read it back before activation.`))throw new Error("Publication cancelled.");const prepared=await signedRequest({action:"prepare-brand-publication",requestId:row.requestId});await publishVerifiedEvent(prepared.request.event,relayConfig.writeRelays,1,authenticateWithBrowserExtension);const confirmed=await signedRequest({action:"confirm-brand-publication",requestId:row.requestId});setRows(current=>{const next=current.map(item=>item.requestId===row.requestId?{...item,state:"active" as const}:item);announcePendingRequestCount(next.filter(item=>item.state!=="active").length,"pro-activations");return next;});setMessage(confirmed.request.message);});}
 const open=rows.filter(row=>row.state!=="active"),completed=rows.filter(row=>row.state==="active");
 const identity=(row:ReviewRow)=><><Image unoptimized src={row.profile.banner} alt={`${row.profile.name} profile banner`} width={750} height={250} style={{width:"100%",maxWidth:750,height:"auto"}}/><p><Image unoptimized src={row.profile.picture} alt={`${row.profile.name} avatar`} width={96} height={96} style={{borderRadius:"50%"}}/></p><p>City identity: <code title={nip19.npubEncode(row.brandPubkey)}>{nip19.npubEncode(row.brandPubkey).slice(0,12)}…{nip19.npubEncode(row.brandPubkey).slice(-8)}</code><br/>Artwork revision: <code>{row.profile.revisionId.slice(0,8)}…{row.profile.revisionId.slice(-8)}</code> · artwork v{row.profile.artworkVersion} · signer v{row.profile.signerVersion} · payout v{row.profile.payoutVersion}<br/>Website: <a href={row.profile.website}>{row.profile.website}</a></p></>;
 return <section><h2>Pro city account activations ({open.length})</h2><p>The city name, avatar and banner are generated automatically from the approved city record. Your signature does not edit those fields; it attests that the reviewed city npub is BitcoinWalk&apos;s official identity for this city. Attestation and publication are separate: activation occurs only after a fresh policy check and exact independent relay read-back.</p><button type="button" disabled={busy} onClick={()=>void load()}>{busy?"Working…":"Refresh activation requests"}</button>{message&&<p role="status">{message}</p>}{open.map(row=><article key={row.requestId}><h3>{row.profile.name}</h3>{identity(row)}<p>Proofs: <strong>{row.proofsReady?"ready":"missing"}</strong><br/>State: <strong>{row.state==="approved"?"attested privately — ready to publish":"awaiting attestation"}</strong>{row.state==="pending"&&<><br/>Proof request expires: {new Date(row.expiresAt*1000).toLocaleString()}</>}</p>{row.state==="pending"?<button type="button" disabled={busy||!row.proofsReady} onClick={()=>approve(row)}>Attest official city identity</button>:<button type="button" disabled={busy} onClick={()=>publish(row)}>Publish and verify city identity</button>}</article>)}{completed.length>0&&<details><summary>Completed activations ({completed.length})</summary>{completed.map(row=><article key={row.requestId}><h3>{row.profile.name}</h3>{identity(row)}<p>State: <strong>active — official city identity published and verified</strong></p></article>)}</details>}</section>;
}
