"use client";

import {useCallback,useEffect,useRef,useState,type Ref} from "react";
import {finalizeEvent,generateSecretKey,getPublicKey,nip19,type EventTemplate} from "nostr-tools";
import {getBrowserExtensionPubkey,type NostrBrowserExtension} from "../nostr/signer";
import {validOrganizerKey} from "../nostr/organizer-identity";

type LoginController={launch:(screen?:"welcome"|"switch-account")=>Promise<void>};
let loginReady:Promise<LoginController>|null=null;
function prepareRemoteLogin(){if(!loginReady)loginReady=import("nostr-login").then(async module=>{const login=new module.NostrLoginInitializer(),service=login.authNostrService;service.getNostrConnectServices=async()=>{const base=await service.createNostrConnect(),relay="wss://relay.nsec.app/",connection=`${base}&relay=${relay}`;return[base,[{name:"Nsec.app",domain:"nsec.app",canImport:true,img:"https://nsec.app/assets/favicon.ico",link:`https://use.nsec.app/${connection}`,relay},{name:"Other key stores",img:"",link:connection,relay}]];};await login.init({noBanner:true,methods:["connect"],bunkers:"nsec.app",perms:"sign_event:31923,sign_event:30303,sign_event:30309,sign_event:22242",title:"Connect a remote signer",description:"Keep your private key in a separate signer and approve BitcoinWalk requests remotely."});return login;});return loginReady;}
function downloadPrivateKey(nsec:string){const text=["BitcoinWalk Nostr account backup","","PRIVATE KEY — KEEP SECRET","Anyone with this nsec can control your Nostr identity.","Never upload it or share it with BitcoinWalk support.","","nsec:",nsec,"","RECOMMENDED NEXT STEP","On desktop, import this nsec into a trusted Nostr browser-extension signer.","On mobile, import it into a signer app such as Amber or Clave and connect through a bunker/remote-signer link.","Delete insecure extra copies and keep one protected offline backup."].join("\n"),url=URL.createObjectURL(new Blob([text],{type:"text/plain;charset=utf-8"})),anchor=document.createElement("a");anchor.href=url;anchor.download=`bitcoinwalk-nostr-key-${new Date().toISOString().slice(0,10)}.txt`;anchor.hidden=true;document.body.appendChild(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function localSigner(secretKey:Uint8Array):NostrBrowserExtension{const pubkey=getPublicKey(secretKey);return{getPublicKey:async()=>pubkey,signEvent:async(template:EventTemplate)=>finalizeEvent(structuredClone(template),secretKey)};}
function decodeNsec(value:string){const decoded=nip19.decode(value.trim());if(decoded.type!=="nsec"||!(decoded.data instanceof Uint8Array))throw new Error("Enter a valid private key beginning with nsec1.");return decoded.data;}

export default function OrganizerIdentity({disabled,onIdentityChange,headingRef}:{disabled:boolean;onIdentityChange:(key:string|null)=>void;headingRef?:Ref<HTMLHeadingElement>}){
 const [pubkey,setPubkey]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[advanced,setAdvanced]=useState(false),[secretInput,setSecretInput]=useState("");
 const active=useRef(true),originalSigner=useRef<NostrBrowserExtension|undefined>(undefined),localSession=useRef(false);
 const connected=useCallback((key:string,note="")=>{const valid=validOrganizerKey(key);setPubkey(valid);onIdentityChange(valid);setMessage(note);},[onIdentityChange]);
 const readIdentity=useCallback(async()=>{connected(await getBrowserExtensionPubkey());},[connected]);
 useEffect(()=>{active.current=true;originalSigner.current=window.nostr;const auth=(event:Event)=>{const detail=(event as CustomEvent<{type?:string}>).detail;if(detail?.type==="logout"){setPubkey(null);onIdentityChange(null);return;}void readIdentity();};document.addEventListener("nlAuth",auth);return()=>{active.current=false;document.removeEventListener("nlAuth",auth);if(localSession.current)window.nostr=originalSigner.current;};},[onIdentityChange,readIdentity]);
 async function run(action:()=>Promise<void>){if(disabled||busy)return;setBusy(true);setMessage("");try{await action();}catch(error){if(active.current)setMessage(error instanceof Error?error.message:"Could not connect this account.");}finally{if(active.current)setBusy(false);}}
 function installLocal(secretKey:Uint8Array,note:string){if(originalSigner.current&&!localSession.current)throw new Error("A browser signer is already installed. Use it below, or open BitcoinWalk in a browser profile without that extension to create a separate account.");window.nostr=localSigner(secretKey);localSession.current=true;connected(getPublicKey(secretKey),note);}
 async function createAccount(){await run(async()=>{const secret=generateSecretKey(),nsec=nip19.nsecEncode(secret);downloadPrivateKey(nsec);installLocal(secret,"Account created. Your private-key backup was downloaded—store it safely before continuing.");});}
 async function connectExtension(){await run(readIdentity);}
 async function importKey(){await run(async()=>{const secret=decodeNsec(secretInput);installLocal(secret,"Private key loaded for this page only.");setSecretInput("");});}
 async function connectRemote(){await run(async()=>{const login=await prepareRemoteLogin();void login.launch("welcome").catch(error=>setMessage(error instanceof Error?error.message:"Remote signer could not be opened."));});}
 function disconnect(){if(localSession.current){window.nostr=originalSigner.current;localSession.current=false;}setPubkey(null);onIdentityChange(null);setMessage("");setAdvanced(false);}
 const npub=pubkey?nip19.npubEncode(pubkey):"";
 return <section className="nostr-onboarding" aria-labelledby="organizer-identity-heading"><div className="nostr-onboarding__intro"><span className="nostr-onboarding__key" aria-hidden="true">⚿</span><h2 ref={headingRef} tabIndex={-1} id="organizer-identity-heading">Step 2 of 3 — Your account</h2><p>Create a new Nostr identity, or connect one you already use.</p></div>{!pubkey?<div className="nostr-onboarding__actions"><button className="nostr-onboarding__primary" type="button" disabled={disabled||busy} onClick={createAccount}>{busy?"Please wait…":"Create new account"}</button><div className="nostr-onboarding__divider"><span>or connect</span></div><button type="button" disabled={disabled||busy} onClick={connectExtension}>Use browser extension</button><button className="nostr-onboarding__advanced-toggle" type="button" aria-expanded={advanced} onClick={()=>setAdvanced(value=>!value)}>{advanced?"Hide other sign-in options":"Use a private key or remote signer"}</button>{advanced&&<div className="nostr-onboarding__advanced"><label>Private key <input type="password" autoComplete="off" spellCheck={false} value={secretInput} onChange={event=>setSecretInput(event.target.value)} placeholder="nsec1…"/></label><button type="button" disabled={disabled||busy||!secretInput.trim()} onClick={importKey}>Use key for this page</button><p className="nostr-onboarding__or">or</p><button type="button" disabled={disabled||busy} onClick={connectRemote}>Connect remote signer</button></div>}</div>:<div className="nostr-onboarding__connected"><span aria-hidden="true">✓</span><p><strong>Account connected</strong><br/><code title={npub}>{npub.slice(0,12)}…{npub.slice(-8)}</code></p><button type="button" disabled={disabled||busy} onClick={disconnect}>Use another account</button></div>}<p className="nostr-onboarding__privacy"><small>Your private key stays in this browser. BitcoinWalk does not upload or store it. Locally created accounts receive a one-time text backup.</small></p>{message&&<p className="nostr-onboarding__message" role="status">{message}</p>}</section>;
}
