"use client";

import {useCallback,useEffect,useRef,useState,type Ref} from "react";
import {finalizeEvent,generateSecretKey,getPublicKey,nip19,type EventTemplate} from "nostr-tools";
import {BunkerSigner,parseBunkerInput} from "nostr-tools/nip46";
import {getBrowserExtensionPubkey,type NostrBrowserExtension} from "../nostr/signer";
import {validOrganizerKey} from "../nostr/organizer-identity";

function downloadPrivateKey(nsec:string){const text=["BitcoinWalk Nostr account backup","","PRIVATE KEY — KEEP SECRET","Anyone with this nsec can control your Nostr identity.","Never upload it or share it with BitcoinWalk support.","","nsec:",nsec,"","RECOMMENDED NEXT STEP","On desktop, import this nsec into a trusted Nostr browser-extension signer.","On mobile, import it into a signer app such as Amber or Clave and connect through a bunker/remote-signer link.","Delete insecure extra copies and keep one protected offline backup."].join("\n"),url=URL.createObjectURL(new Blob([text],{type:"text/plain;charset=utf-8"})),anchor=document.createElement("a");anchor.href=url;anchor.download=`bitcoinwalk-nostr-key-${new Date().toISOString().slice(0,10)}.txt`;anchor.hidden=true;document.body.appendChild(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function localSigner(secretKey:Uint8Array):NostrBrowserExtension{const pubkey=getPublicKey(secretKey);return{getPublicKey:async()=>pubkey,signEvent:async(template:EventTemplate)=>finalizeEvent(structuredClone(template),secretKey)};}
function decodeNsec(value:string){const decoded=nip19.decode(value.trim());if(decoded.type!=="nsec"||!(decoded.data instanceof Uint8Array))throw new Error("Enter a valid private key beginning with nsec1.");return decoded.data;}
function remoteSigner(signer:BunkerSigner):NostrBrowserExtension{return{getPublicKey:()=>signer.getPublicKey(),signEvent:template=>signer.signEvent(template),nip44:{encrypt:(pubkey,plaintext)=>signer.nip44Encrypt(pubkey,plaintext)}};}

export default function OrganizerIdentity({disabled,onIdentityChange,headingRef}:{disabled:boolean;onIdentityChange:(key:string|null)=>void;headingRef?:Ref<HTMLHeadingElement>}){
 const [pubkey,setPubkey]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[signerInput,setSignerInput]=useState("");
 const active=useRef(true),originalSigner=useRef<NostrBrowserExtension|undefined>(undefined),customSession=useRef(false),remoteSession=useRef<BunkerSigner|null>(null);
 const connected=useCallback((key:string,note="")=>{const valid=validOrganizerKey(key);setPubkey(valid);onIdentityChange(valid);setMessage(note);},[onIdentityChange]);
 const readIdentity=useCallback(async()=>{connected(await getBrowserExtensionPubkey());},[connected]);
 useEffect(()=>{active.current=true;originalSigner.current=window.nostr;return()=>{active.current=false;if(customSession.current)window.nostr=originalSigner.current;void remoteSession.current?.close();};},[]);
 async function run(action:()=>Promise<void>){if(disabled||busy)return;setBusy(true);setMessage("");try{await action();}catch(error){if(active.current)setMessage(error instanceof Error?error.message:"Could not connect this account.");}finally{if(active.current)setBusy(false);}}
 async function clearCustomSigner(){if(remoteSession.current){await remoteSession.current.close();remoteSession.current=null;}if(customSession.current)window.nostr=originalSigner.current;customSession.current=false;}
 async function installSigner(signer:NostrBrowserExtension,note:string,remote:BunkerSigner|null=null){const key=await signer.getPublicKey();validOrganizerKey(key);await clearCustomSigner();window.nostr=signer;customSession.current=true;remoteSession.current=remote;connected(key,note);}
 async function installLocal(secretKey:Uint8Array,note:string){await installSigner(localSigner(secretKey),note);}
 async function createAccount(){await run(async()=>{const secret=generateSecretKey(),nsec=nip19.nsecEncode(secret);downloadPrivateKey(nsec);await installLocal(secret,"Account created. Your private-key backup was downloaded—store it safely before continuing.");});}
 async function connectExtension(){await run(async()=>{await clearCustomSigner();await readIdentity();});}
 async function connectSigner(){await run(async()=>{const input=signerInput.trim();if(input.startsWith("nsec1")){await installLocal(decodeNsec(input),"Private key loaded for this page only.");}else if(input.startsWith("bunker://")){const pointer=await parseBunkerInput(input);if(!pointer)throw new Error("Enter a valid bunker:// signer connection.");const signer=BunkerSigner.fromBunker(generateSecretKey(),pointer,{onauth:url=>window.open(url,"_blank","noopener,noreferrer")});try{await signer.connect({name:"BitcoinWalk",url:window.location.origin});await installSigner(remoteSigner(signer),"Remote signer connected.",signer);}catch(error){await signer.close();throw error;}}else throw new Error("Enter an nsec1 private key or a bunker:// signer connection.");setSignerInput("");});}
 function disconnect(){void clearCustomSigner();setPubkey(null);onIdentityChange(null);setMessage("");}
 const npub=pubkey?nip19.npubEncode(pubkey):"";
 return <section className="nostr-onboarding" aria-labelledby="organizer-identity-heading"><div className="nostr-onboarding__intro"><span className="nostr-onboarding__key" aria-hidden="true">⚿</span><h2 ref={headingRef} tabIndex={-1} id="organizer-identity-heading">Step 2 of 3 — Your account</h2><p>Create a new Nostr identity, or connect one you already use.</p></div>{!pubkey?<div className="nostr-onboarding__actions"><button type="button" disabled={disabled||busy} onClick={createAccount}>{busy?"Please wait…":"Create new account"}</button><div className="nostr-onboarding__divider"><span>or connect</span></div><button className="nostr-onboarding__primary" type="button" disabled={disabled||busy} onClick={connectExtension}>Connect with browser extension</button><p className="nostr-onboarding__recommendation">Recommended on desktop</p><div className="nostr-onboarding__divider"><span>OR</span></div><div className="nostr-onboarding__advanced"><label>Private key or signer <input type="password" autoComplete="off" spellCheck={false} value={signerInput} onChange={event=>setSignerInput(event.target.value)} placeholder="nsec1… or bunker://…"/></label><button className="nostr-onboarding__primary" type="button" disabled={disabled||busy||!signerInput.trim()} onClick={connectSigner}>Connect</button><p className="nostr-onboarding__recommendation">On mobile, use a bunker:// connection from a remote signer such as Amber. Your signer keeps your private key.</p></div></div>:<div className="nostr-onboarding__connected"><span aria-hidden="true">✓</span><p><strong>Account connected</strong><br/><code title={npub}>{npub.slice(0,12)}…{npub.slice(-8)}</code></p><button type="button" disabled={disabled||busy} onClick={disconnect}>Use another account</button></div>}<p className="nostr-onboarding__privacy"><small>Your private key stays in this browser or your remote signer. BitcoinWalk does not upload or store it. Locally created accounts receive a one-time text backup.</small></p>{message&&<p className="nostr-onboarding__message" role="status">{message}</p>}</section>;
}
