"use client";
/* eslint-disable @next/next/no-img-element -- Private, locally verified data URL; never send pending artwork to an image proxy. */
import {useRef,useState} from "react";
import {useDashboard,useDashboardAutoLoad} from "./dashboard-context";
import {isSuperAdmin} from "../nostr/authority";
import {getBrowserExtensionPubkey,signWithBrowserExtension,authenticateWithBrowserExtension} from "../nostr/signer";
import {mediaRequestTemplate} from "../domain/media-request";
import {assertExactSigned} from "../nostr/moderation";
import {publishVerifiedEvent} from "../nostr/relay";
import {relayConfig} from "../lib/relay-config";
import {createSponsorshipRevision,latestSponsorships,querySponsorships,sponsorshipKey,type SponsorshipRevision} from "../nostr/sponsorships";
type Review={hash:string;base64:string;revisionId:string};
export default function SponsorLogoReview({scopeKey,onChanged}:{scopeKey:string;onChanged:()=>Promise<void>}){
 const dashboard=useDashboard(),lock=useRef(false);
 const [rows,setRows]=useState<SponsorshipRevision[]>([]),[selected,setSelected]=useState(""),[review,setReview]=useState<Review|null>(null),[message,setMessage]=useState("Load assignments to review uploaded artwork."),[busy,setBusy]=useState(false);
 const current=rows.find(row=>row.event.id===selected);
 async function checkActor(){const actor=await getBrowserExtensionPubkey();if(!isSuperAdmin(actor)||actor!==dashboard.pubkey)throw new Error("Connect the super-admin identity.");return actor;}
 async function load(){if(lock.current)return;lock.current=true;setBusy(true);try{await checkActor();const next=latestSponsorships(await querySponsorships(relayConfig.readRelays)).filter(row=>row.sponsorship.mode==="sponsor"&&sponsorshipKey(row.sponsorship.scope)===scopeKey);setRows(next);setSelected(next[0]?.event.id??"");setReview(null);setMessage("Load the logo uploaded for the assignment selected above.");}catch(error){setMessage(error instanceof Error?error.message:"Could not load assignments.");}finally{lock.current=false;setBusy(false);}}
 useDashboardAutoLoad(load);
 async function inspect(){if(lock.current||!current)return;lock.current=true;setBusy(true);setReview(null);try{await checkActor();const template=mediaRequestTemplate({action:"review-sponsor-logo",cityId:current.sponsorship.scope.cityId,sponsorPubkey:current.sponsorship.sponsorPubkey!}),event=await signWithBrowserExtension(template);assertExactSigned(event,template);const response=await fetch("/api/sponsors/logo/review",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({event})}),body=await response.json();if(!response.ok)throw new Error(body.error||"Review failed.");if(!/^[a-f0-9]{64}$/.test(body.hash)||typeof body.base64!=="string")throw new Error("Invalid review response.");const bytes=Uint8Array.from(atob(body.base64),c=>c.charCodeAt(0)),hash=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",bytes))).map(x=>x.toString(16).padStart(2,"0")).join("");if(hash!==body.hash)throw new Error("Logo integrity check failed.");setReview({...body,revisionId:current.event.id});setMessage("Check this exact artwork. Approval will sign its hash into the selected assignment.");}catch(error){setMessage(error instanceof Error?error.message:"Review failed.");}finally{lock.current=false;setBusy(false);}}
 async function approve(clear=false){if(lock.current||!current||!clear&&review?.revisionId!==current.event.id)return;lock.current=true;setBusy(true);try{const actor=await checkActor();const latest=latestSponsorships(await querySponsorships(relayConfig.readRelays)).find(row=>sponsorshipKey(row.sponsorship.scope)===sponsorshipKey(current.sponsorship.scope));if(latest?.event.id!==current.event.id)throw new Error("Assignment changed. Reload before approving.");const value={...current.sponsorship,version:2 as const,previousRevisionId:current.event.id,logoHash:clear?undefined:review!.hash},template=createSponsorshipRevision(value);const event=await signWithBrowserExtension(template);assertExactSigned(event,template);if(event.pubkey!==actor)throw new Error("Signer changed.");await publishVerifiedEvent(event,relayConfig.writeRelays,1,authenticateWithBrowserExtension);setRows(rows.map(row=>row.event.id===current.event.id?{event,sponsorship:value}:row));setSelected(event.id);setReview(null);setMessage(clear?"Logo removed from the signed assignment. Sponsorship remains active.":"Exact logo approved in the signed assignment. Preview artwork will include it only while sponsorship is enabled and active.");await onChanged();}catch(error){setMessage(error instanceof Error?error.message:"Approval failed.");}finally{lock.current=false;setBusy(false);}}
 return <section><h2>Review and approve logo</h2><p>Uploading alone never approves a logo. Each approval or removal requires the super-admin signature.</p><button disabled={busy} onClick={()=>void load()}>Refresh assignments</button>{current&&<><p>Approved logo hash: {current.sponsorship.logoHash??"None"}</p><button disabled={busy} onClick={()=>void inspect()}>Load pending logo for review</button>{current.sponsorship.logoHash&&<button disabled={busy} onClick={()=>void approve(true)}>Sign and remove logo</button>}</>}{review&&<><div style={{background:"#888",padding:24}}><img src={`data:image/png;base64,${review.base64}`} alt="Pending sponsor artwork for review" style={{maxWidth:400,maxHeight:240}}/></div><p>Exact asset: {review.hash}</p><button disabled={busy||review.revisionId!==current?.event.id} onClick={()=>void approve()}>Sign and approve this exact logo</button></>}<p role="status">{message}</p></section>;
}
