import {mkdtemp,writeFile,mkdir,symlink} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {DatabaseSync} from "node:sqlite";
import {describe,expect,it} from "vitest";
import {PaymentStore} from "../payments/service";
import {LogoJobStore} from "./approval-worker";
import {LogoCatalog} from "./catalog";
import {cityLogoVariants} from "./inkscape-source";

const cityId="032d98ea-f5da-4826-95bd-c4cf9286716e",revisionId="a".repeat(64),jobKey="b".repeat(64);
function setup(){const db=new DatabaseSync(":memory:");const payments=new PaymentStore(db),jobs=new LogoJobStore(db,0);const candidate={jobKey,cityId,revisionId,approvalId:"c".repeat(64),decisionAt:1,cityName:"Warszawa",slug:"warszawa",locale:"pl-PL",templateVersion:"city-logo-inkscape-v1"};jobs.reconcile([candidate],1);const claimed=jobs.claim(1,300)!;return {db,payments,jobs,claimed,catalog:new LogoCatalog(jobs,payments)};}
async function artifact(){const root=await mkdtemp(join(tmpdir(),"bw-logo-catalog-")),path=join(root,"warszawa");await mkdir(path);const files=cityLogoVariants.map((variant,index)=>({name:`warszawa-${variant}.png`,label:variant,background:variant.endsWith("black")?"dark":"light",width:100,height:100,sha256:"",transparent:true,data:Buffer.from(`png-${index}`)}));const {createHash}=await import("node:crypto");for(const file of files){await writeFile(join(path,file.name),file.data);file.sha256=createHash("sha256").update(file.data).digest("hex");}const archive=Buffer.from("zip");await writeFile(join(path,"warszawa-logos.zip"),archive);await writeFile(join(path,"manifest.json"),JSON.stringify({version:1,cityId,slug:"warszawa",cityName:"Warszawa",locale:"pl-PL",source:"bitcoinwalk:city-logo-renderer",templateVersion:"city-logo-inkscape-v1",files:files.map(file=>({name:file.name,label:file.label,background:file.background,width:file.width,height:file.height,sha256:file.sha256,transparent:file.transparent})),archive:{name:"warszawa-logos.zip",sha256:createHash("sha256").update(archive).digest("hex")}}));return path;}
describe("durable city logo catalog",()=>{
 it("serves only the ready job for the exact approved revision and derives visibility from entitlement",async()=>{const x=setup(),path=await artifact();x.jobs.recordArtifact(jobKey,x.claimed.leaseToken!,path,2);x.jobs.complete(jobKey,x.claimed.leaseToken!,2);expect((await x.catalog.ready({cityId,revisionId,slug:"warszawa"}))?.publiclyListed).toBe(false);x.db.prepare("INSERT INTO paid_city_entitlement VALUES (?,?,?,?,?)").run(cityId,"owner","d".repeat(64),"invoice",2);expect((await x.catalog.ready({cityId,revisionId,slug:"warszawa"}))?.publiclyListed).toBe(true);expect(await x.catalog.ready({cityId,revisionId:"e".repeat(64),slug:"warszawa"})).toBeNull();});
 it("uses the current ready city pack for walks published against an older city revision",async()=>{const x=setup(),path=await artifact();x.jobs.recordArtifact(jobKey,x.claimed.leaseToken!,path,2);x.jobs.complete(jobKey,x.claimed.leaseToken!,2);expect((await x.catalog.readyForCity({cityId,slug:"warszawa"}))?.revisionId).toBe(revisionId);expect(await x.catalog.readyForCity({cityId,slug:"wrong"})).toBeNull();x.db.prepare("UPDATE city_logo_job SET state='obsolete' WHERE jobKey=?").run(jobKey);expect(await x.catalog.readyForCity({cityId,slug:"warszawa"})).toBeNull();});
 it("does not serve queued, failed, obsolete, corrupt, unlisted or symlinked files",async()=>{const x=setup();expect(await x.catalog.ready({cityId,revisionId,slug:"warszawa"})).toBeNull();const path=await artifact(),file=`warszawa-${cityLogoVariants[0]}.png`;x.jobs.recordArtifact(jobKey,x.claimed.leaseToken!,path,2);x.jobs.complete(jobKey,x.claimed.leaseToken!,2);await expect(x.catalog.file(jobKey,"../payments.sqlite")).resolves.toBeNull();await expect(x.catalog.file(jobKey,"unknown.png")).resolves.toBeNull();await symlink(join(path,file),join(path,"link.png"));await expect(x.catalog.file(jobKey,"link.png")).resolves.toBeNull();await writeFile(join(path,file),"changed");await expect(x.catalog.file(jobKey,file)).rejects.toThrow("checksum");x.db.prepare("UPDATE city_logo_job SET state='obsolete' WHERE jobKey=?").run(jobKey);expect(await x.catalog.file(jobKey,"warszawa-logos.zip")).toBeNull();});
});
