import {DatabaseSync} from "node:sqlite";
import {afterEach,describe,expect,it,vi} from "vitest";
import {PayoutLedger} from "./payout-ledger";
import {PayoutAuthorityStore} from "./payout-authority";
import {PayoutInvoiceIntake,PAYOUT_INVOICE_API} from "./payout-intake";
import {PayoutControlApi} from "./payout-control-api";
import type {PayoutInvoiceIssuer} from "./payout-invoice-issuer";
import type {ProvisionConfig} from "./contract";
const dbs:DatabaseSync[]=[];afterEach(()=>dbs.splice(0).forEach(db=>db.close()));
const tokens={intake:"i".repeat(48),issuer:"s".repeat(48),receipt:"r".repeat(48),authority:"a".repeat(48),operations:"o".repeat(48)},auth=(value:string)=>`Bearer ${value}`,now=1800000000;
const config:ProvisionConfig={cityId:"00000000-0000-4000-8000-000000000001",version:1,domain:"bitcoinwalk.org",localPart:"madeira",brandPubkey:"a".repeat(64),authorityEventId:"b".repeat(64),approvalEventId:"c".repeat(64),brandEventId:"d".repeat(64),payoutVersion:2,payoutDestination:"organizer@example.org",walletRef:"bitcoinwalk-rustress",organizerBasisPoints:7900,retainedBasisPoints:2100,invoiceIssuance:"disabled"};
describe("private payout control API",()=>{
 function fixture(on=true){const db=new DatabaseSync(":memory:");dbs.push(db);const ledger=new PayoutLedger(db),authority=new PayoutAuthorityStore(db),intake=new PayoutInvoiceIntake(ledger,async(city,version)=>authority.resolve(city,version),()=>now),issuer={issue:vi.fn(async()=>({invoice:"lnbc",paymentHash:"ab".repeat(32),amountMsat:"100000",issuedAt:now,expiresAt:now+3600})),receiptEvidence:vi.fn(async()=>({api:"bitcoinwalk-zap-settlement-v1",paymentHash:"ab".repeat(32)})),status:()=>({invoiceIssued:1,invoiceCreatedPendingIntake:0,invoiceOutcomesUnknown:0})} as unknown as PayoutInvoiceIssuer;return {ledger,issuer,api:new PayoutControlApi(authority,intake,ledger,"bitcoinwalk-rustress",()=>on,()=>({running:on,ready:on,consecutiveFailures:0}),tokens,issuer)};}
 it("separates authority, intake and aggregate operations credentials",async()=>{const f=fixture();expect((await f.api.route("POST","/v1/authority",auth(tokens.authority),config)).status).toBe(200);const request={api:PAYOUT_INVOICE_API,cityId:config.cityId,payoutVersion:2,paymentHash:"ab".repeat(32),amountMsat:"100000",issuedAt:now,expiresAt:now+3600};expect((await f.api.route("POST","/v1/invoices",auth(tokens.intake),request)).status).toBe(200);const status=await f.api.route("GET","/v1/status",auth(tokens.operations));expect(status).toMatchObject({status:200,body:{authorityRecords:1,invoices:1,pendingIncoming:1,enabled:true}});expect(JSON.stringify(status)).not.toContain("organizer@example.org");});
 it("keeps invoice intake disabled while allowing safe authority preparation",async()=>{const f=fixture(false);expect((await f.api.route("POST","/v1/authority",auth(tokens.authority),config)).status).toBe(200);expect((await f.api.route("POST","/v1/invoices",auth(tokens.intake),{})).status).toBe(503);expect(f.ledger.operationalStatus("bitcoinwalk-rustress").invoices).toBe(0);});
 it("uses a separate issuer credential and only returns an invoice while runtime is ready",async()=>{const f=fixture();expect((await f.api.route("POST","/v1/invoices/issue",auth(tokens.issuer),{request:"exact"})).status).toBe(200);expect(f.issuer.issue).toHaveBeenCalledOnce();expect((await f.api.route("POST","/v1/invoices/issue",auth(tokens.intake),{})).status).toBe(401);expect((await fixture(false).api.route("POST","/v1/invoices/issue",auth(tokens.issuer),{})).status).toBe(503);});
 it("exposes settlement evidence only on the dedicated Unix transport",async()=>{const f=fixture();expect((await f.api.route("POST","/v1/receipts/evidence",auth(tokens.receipt),{claim:"exact"})).status).toBe(404);expect(f.issuer.receiptEvidence).not.toHaveBeenCalled();expect((await f.api.route("POST","/v1/receipts/evidence",auth(tokens.receipt),{claim:"exact"},"receipt-evidence")).status).toBe(200);expect(f.issuer.receiptEvidence).toHaveBeenCalledOnce();for(const wrong of [tokens.intake,tokens.issuer,tokens.authority,tokens.operations])expect((await f.api.route("POST","/v1/receipts/evidence",auth(wrong),{},"receipt-evidence")).status).toBe(401);expect((await fixture(false).api.route("POST","/v1/receipts/evidence",auth(tokens.receipt),{},"receipt-evidence")).status).toBe(503);});
 it("rejects cross-role, malformed and unauthenticated requests without details",async()=>{const f=fixture();expect((await f.api.route("POST","/v1/authority",auth(tokens.intake),config)).status).toBe(401);expect((await f.api.route("POST","/v1/invoices",auth(tokens.authority),{})).status).toBe(401);expect((await f.api.route("GET","/v1/status",undefined)).status).toBe(401);expect((await f.api.route("POST","/v1/authority",auth(tokens.authority),{...config,nwc:"secret"}))).toEqual({status:409,body:{error:"request-rejected"}});});
});
