import {DatabaseSync} from "node:sqlite";
import {afterEach,describe,expect,it} from "vitest";
import {PayoutLedger} from "./payout-ledger";
import {PayoutHostEvidence,PAYOUT_HOST_EVIDENCE_CONTRACT} from "./payout-host-evidence";
import {RUSTRESS_WALLET_REQUIREMENTS} from "./contract";
const dbs:DatabaseSync[]=[];afterEach(()=>dbs.splice(0).forEach(db=>db.close()));
const now=1800000000,binding="ab".repeat(32),serviceId="ce72e914-5890-4902-8e8c-16fb30d80f11",fence="19d4c97a-aef0-43d7-b9bd-245b934d9e54";
const config={contract:PAYOUT_HOST_EVIDENCE_CONTRACT,release:"0.2.0",binding,journalServiceId:serviceId,walletRef:"bitcoinwalk-rustress",checkoutConnectionRef:"bitcoinwalk-checkout",connectionStartedAt:now-1000,retainedFrom:now-1000,approvedAt:now-100,expiresAt:now+86400,budgetMsat:"797900000",maximumPayoutMsat:"790000000",maximumFeeMsat:"7900000",grantedMethods:[...RUSTRESS_WALLET_REQUIREMENTS.methods,"get_balance","notifications"],notificationsGranted:true as const,isolated:true as const,exclusiveConnection:true as const,inventoryVerified:true as const,separateHost:true as const,privateTransport:true as const,backupRestoreVerified:true as const,hubVersion:"1.24.0" as const,backend:"ldk" as const,feePolicy:"ldk-native-v1" as const,acceptedPriorSpends:[]};
describe("host-derived payout evidence",()=>{
 function fixture(active=true,enabled=true){const db=new DatabaseSync(":memory:");dbs.push(db);const ledger=new PayoutLedger(db),journal=async()=>({serviceId,binding,fence,active,lastSequence:0});return {ledger,evidence:new PayoutHostEvidence(config,ledger,journal,()=>enabled,()=>now)};}
 it("builds fresh deployment, wallet, Hub and history evidence from one pinned inventory",async()=>{const f=fixture();expect(await f.evidence.deployment()).toMatchObject({serviceId,binding,privateTransport:true,separateHost:true});expect(f.evidence.evidence().readiness.inventory.remainingBudgetMsat).toBe(797900000);expect(f.evidence.hubSafety()).toMatchObject({binding,hubVersion:"1.24.0"});expect(await f.evidence.coverage()).toMatchObject({binding,fenceId:fence,exclusive:true});expect(f.evidence.policy()).toMatchObject({budgetMsat:"797900000",maximumPayoutMsat:"790000000"});});
 it("deducts an accepted historical payout and lowers the effective payout ceiling",()=>{const spend={paymentHash:"12".repeat(32),amountMsat:"79000",feeMsat:"1786",createdAt:now-500,settledAt:now-490};const db=new DatabaseSync(":memory:");dbs.push(db);const evidence=new PayoutHostEvidence({...config,acceptedPriorSpends:[spend]},new PayoutLedger(db),async()=>({serviceId,binding,fence,active:true,lastSequence:0}),()=>true,()=>now);const readiness=evidence.evidence().readiness;expect(readiness.inventory.remainingBudgetMsat).toBe(797819214);expect(readiness.policy.maximumTestPaymentMsat).toBe(789919214);expect(evidence.policy().acceptedPriorSpentMsat).toBe("80786");});
 it("issues exact native-fee permits only while enabled and within policy",async()=>{const f=fixture();const base={binding,paymentHash:"cd".repeat(32),amountMsat:"79000",maximumFeeMsat:"10000"};expect(await f.evidence.permit(base)).toMatchObject({enforcedFeeCeilingMsat:"10000",authorized:true});expect(await f.evidence.permit({...base,amountMsat:"790000000",maximumFeeMsat:"7900000"})).toMatchObject({enforcedFeeCeilingMsat:"7900000"});expect(await f.evidence.permit({...base,maximumFeeMsat:"9999"})).toBeNull();expect(await fixture(true,false).evidence.permit(base)).toBeNull();});
 it("blocks a paused/mismatched journal and exhausted host evidence",async()=>{await expect(fixture(false).evidence.coverage()).rejects.toThrow();const db=new DatabaseSync(":memory:");dbs.push(db);const bad=new PayoutHostEvidence(config,new PayoutLedger(db),async()=>({serviceId,binding:"cd".repeat(32),fence,active:true,lastSequence:0}),()=>true,()=>now);await expect(bad.deployment()).rejects.toThrow();expect(()=>new PayoutHostEvidence({...config,expiresAt:now},new PayoutLedger(db),async()=>({serviceId,binding,fence,active:true,lastSequence:0}),()=>true,()=>now).evidence()).toThrow();});
});
