import {createHash,randomUUID} from "node:crypto";
import {DatabaseSync} from "node:sqlite";
import {afterEach,describe,expect,it,vi} from "vitest";
import {encode,sign as signBolt} from "bolt11";
import {finalizeEvent,getPublicKey,type Event,type EventTemplate} from "nostr-tools";
import {ZapReceiptAuthority,ZAP_RECEIPT_API} from "./zap-receipt-authority";

const dbs:DatabaseSync[]=[];afterEach(()=>dbs.splice(0).forEach(db=>db.close()));
const payerKey=new Uint8Array(32).fill(2),signerKey=new Uint8Array(32).fill(3),recipient=getPublicKey(new Uint8Array(32).fill(4)),signerPubkey=getPublicKey(signerKey),now=1_800_000_000,preimage="12".repeat(32),hash=createHash("sha256").update(Buffer.from(preimage,"hex")).digest("hex");
function fixture(patch:Record<string,unknown>={}){
 const request=finalizeEvent({kind:9734,created_at:now-10,content:"Walk on!",tags:[["relays","wss://one.example","wss://two.example"],["amount","100000"],["p",recipient],["e","ab".repeat(32)],["k","31923"]]},payerKey),raw=JSON.stringify(request),descriptionHash=createHash("sha256").update(raw).digest("hex");
 const invoice=signBolt(encode({millisatoshis:"100000",timestamp:now-60,tags:[{tagName:"payment_hash",data:hash},{tagName:"purpose_commit_hash",data:descriptionHash},{tagName:"expire_time",data:3600}]}),"34".repeat(32)).paymentRequest!;
 const claim={api:ZAP_RECEIPT_API,cityId:randomUUID(),payoutVersion:1,paymentHash:hash,recipientPubkey:recipient,amountMsat:"100000",zapRequest:raw},evidence=vi.fn(async()=>({invoice,paymentHash:hash,amountMsat:"100000",descriptionHash,settledAt:now,preimage,...patch}));
 const signer={publicKey:signerPubkey,sign:vi.fn(async(template:EventTemplate)=>finalizeEvent(template,signerKey))},publisher={publish:vi.fn(async(relays:string[],event:Event)=>{void relays;void event;return ["wss://one.example"];})};
 const db=new DatabaseSync(":memory:");dbs.push(db);return {db,claim,evidence,signer,publisher,authority:new ZapReceiptAuthority(db,signer,evidence,publisher)};
}
describe("private NIP-57 receipt authority",()=>{
 it("validates settlement, signs the required receipt and persists it before publication",async()=>{const f=fixture(),result=await f.authority.issue(f.claim);expect(result).toMatchObject({state:"published",relays:["wss://one.example"]});const event=f.publisher.publish.mock.calls[0][1];expect(event).toMatchObject({kind:9735,pubkey:signerPubkey,created_at:now,content:""});expect(event.tags).toEqual(expect.arrayContaining([["p",recipient],["P",getPublicKey(payerKey)],["bolt11",expect.stringMatching(/^lnbc/)],["description",f.claim.zapRequest],["preimage",preimage]]));});
 it("reuses the exact signed receipt after a publication outage and after restart",async()=>{const f=fixture();f.publisher.publish.mockRejectedValueOnce(new Error("offline"));await expect(f.authority.issue(f.claim)).rejects.toThrow();const restarted=new ZapReceiptAuthority(f.db,f.signer,f.evidence,f.publisher);await restarted.issue(f.claim);expect(f.signer.sign).toHaveBeenCalledTimes(1);expect(f.evidence).toHaveBeenCalledTimes(1);expect(f.publisher.publish.mock.calls[0][1]).toEqual(f.publisher.publish.mock.calls[1][1]);});
 it("resumes the exact prepared claim after a signer outage",async()=>{const f=fixture();f.signer.sign.mockRejectedValueOnce(new Error("signer offline"));await expect(f.authority.issue(f.claim)).rejects.toThrow();const restarted=new ZapReceiptAuthority(f.db,f.signer,f.evidence,f.publisher);await expect(restarted.issue(f.claim)).resolves.toMatchObject({state:"published"});expect(f.signer.sign).toHaveBeenCalledTimes(2);});
 it("returns a published receipt idempotently without signing or publishing twice",async()=>{const f=fixture();const first=await f.authority.issue(f.claim),second=await f.authority.issue(f.claim);expect(second).toEqual(first);expect(f.signer.sign).toHaveBeenCalledTimes(1);expect(f.publisher.publish).toHaveBeenCalledTimes(1);});
 it.each(["recipient","amount","signature","relays","uppercase provider"])('rejects invalid zap request: %s',async mode=>{const f=fixture(),event=JSON.parse(f.claim.zapRequest);if(mode==="recipient")event.tags.find((t:string[])=>t[0]==="p")[1]="ff".repeat(32);if(mode==="amount")event.tags.find((t:string[])=>t[0]==="amount")[1]="99000";if(mode==="relays")event.tags.find((t:string[])=>t[0]==="relays").push("http://local");if(mode==="uppercase provider")event.tags.push(["P","ff".repeat(32)]);if(mode==="signature")event.content="altered";f.claim.zapRequest=JSON.stringify(event);await expect(f.authority.issue(f.claim)).rejects.toThrow();expect(f.signer.sign).not.toHaveBeenCalled();});
 it("rejects IP-literal relay hints including bracketed IPv6",async()=>{for(const relay of ["wss://127.0.0.1","wss://[::1]"]){const f=fixture(),event=JSON.parse(f.claim.zapRequest);event.tags.find((tag:string[])=>tag[0]==="relays")[1]=relay;f.claim.zapRequest=JSON.stringify(event);await expect(f.authority.issue(f.claim)).rejects.toThrow();expect(f.signer.sign).not.toHaveBeenCalled();}});
 it.each(["hash","amount","description","preimage"])('rejects mismatched settlement evidence: %s',async mode=>{const patch=mode==="hash"?{paymentHash:"ef".repeat(32)}:mode==="amount"?{amountMsat:"99000"}:mode==="description"?{descriptionHash:"ef".repeat(32)}:{preimage:"56".repeat(32)};const f=fixture(patch);await expect(f.authority.issue(f.claim)).rejects.toThrow("Settlement evidence");expect(f.signer.sign).not.toHaveBeenCalled();});
 it("rejects a signer that changes the receipt",async()=>{const f=fixture();f.signer.sign.mockImplementationOnce(async template=>finalizeEvent({...template,content:"changed"},signerKey));await expect(f.authority.issue(f.claim)).rejects.toThrow("signer");expect(f.publisher.publish).not.toHaveBeenCalled();});
 it("rejects conflicting reuse of a payment hash",async()=>{const f=fixture();await f.authority.issue(f.claim);await expect(f.authority.issue({...f.claim,cityId:randomUUID()})).rejects.toThrow("conflict");});
 it("rejects a conflicting concurrent claim instead of joining the first operation",async()=>{const f=fixture(),proof=await f.evidence();let release!:()=>void;f.evidence.mockImplementationOnce(()=>new Promise(resolve=>{release=()=>resolve(proof);}));const first=f.authority.issue(f.claim);await Promise.resolve();await expect(f.authority.issue({...f.claim,cityId:randomUUID()})).rejects.toThrow("conflict");release();await expect(first).resolves.toMatchObject({state:"published"});});
});
