"use client";
import {useCallback,useRef,useState} from "react";
import {useDashboard,useDashboardAutoLoad} from "../../../components/dashboard-context";
import {DEFAULT_HOME_PAGE,HOME_PAGE_ID,contentPageSchema,type ContentPage} from "../../../domain/content";
import {approvedDirectory} from "../../../domain/directory";
import {directoryConfig} from "../../../lib/directory-config";
import {relayConfig} from "../../../lib/relay-config";
import {isSuperAdmin} from "../../../nostr/authority";
import {queryDirectoryRecords} from "../../../nostr/city-records";
import {createContentRevision,latestContentPages,queryContentRevisions,type ContentRevision} from "../../../nostr/content-records";
import {DEFAULT_FEATURE_FLAGS,type FeatureFlags} from "../../../domain/feature-flags";
import {createFeatureFlagsRevision,latestFeatureFlags,queryFeatureFlags,type FeatureFlagRevision} from "../../../nostr/feature-flags";
import {assertExactSigned} from "../../../nostr/moderation";
import {publishVerifiedEvent} from "../../../nostr/relay";
import {authenticateWithBrowserExtension,getBrowserExtensionPubkey,signWithBrowserExtension} from "../../../nostr/signer";

type Editor={page:ContentPage;revisionId?:string};
export default function ContentPage(){
 const dashboard=useDashboard(),lock=useRef(false),[rows,setRows]=useState<ContentRevision[]>([]),[flagRows,setFlagRows]=useState<FeatureFlagRevision[]>([]),[flags,setFlags]=useState<FeatureFlags>(DEFAULT_FEATURE_FLAGS),[citySlugs,setCitySlugs]=useState<Set<string>>(new Set()),[editor,setEditor]=useState<Editor|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("Connect the super-admin identity to manage public content.");
 const load=useCallback(async(force=false)=>{if((lock.current&&!force)||!dashboard.pubkey)return;if(!force)lock.current=true;setBusy(true);try{const actor=await getBrowserExtensionPubkey();if(!isSuperAdmin(actor)||actor!==dashboard.pubkey)throw new Error("Connect the BitcoinWalk super-admin identity.");const [content,directory,featureFlags]=await Promise.all([queryContentRevisions(relayConfig.readRelays),queryDirectoryRecords(relayConfig.readRelays),queryFeatureFlags(relayConfig.readRelays)]);setRows(content);setFlagRows(featureFlags);setFlags(latestFeatureFlags(featureFlags)?.flags??DEFAULT_FEATURE_FLAGS);setCitySlugs(new Set(approvedDirectory(directory.revisions,directory.approvals,directoryConfig.paidCities).map(row=>row.city.slug)));setMessage("Content loaded. Every published change requires your signature.");}catch(error){setMessage(error instanceof Error?error.message:"Could not load content.");}finally{lock.current=false;setBusy(false);}},[dashboard.pubkey]);
 useDashboardAutoLoad(load);
 const latest=latestContentPages(rows),home=latest.find(row=>row.page.pageId===HOME_PAGE_ID),listed=[{page:home?.page??DEFAULT_HOME_PAGE,revisionId:home?.event.id},...latest.filter(row=>row.page.pageId!==HOME_PAGE_ID).map(row=>({page:row.page,revisionId:row.event.id}))];
 function edit(value:Editor){setEditor({page:{...value.page},revisionId:value.revisionId});setMessage(`Editing ${value.page.pageId===HOME_PAGE_ID?"Homepage":value.page.title}.`);}
 function field<K extends keyof ContentPage>(name:K,value:ContentPage[K]){if(editor)setEditor({...editor,page:{...editor.page,[name]:value}});}
 async function save(){if(!editor||lock.current)return;lock.current=true;setBusy(true);try{const actor=await getBrowserExtensionPubkey();if(!isSuperAdmin(actor)||actor!==dashboard.pubkey)throw new Error("Connect the BitcoinWalk super-admin identity.");const parsed=contentPageSchema.parse({...editor.page,previousRevisionId:editor.revisionId});if(parsed.slug&&citySlugs.has(parsed.slug))throw new Error("That URL is already used by a BitcoinWalk city.");const duplicate=latest.find(row=>row.page.pageId!==parsed.pageId&&row.page.slug===parsed.slug);if(duplicate)throw new Error("That URL is already used by another content page.");const template=createContentRevision(parsed);setMessage("Review and sign this content revision in your extension…");const signed=await signWithBrowserExtension(template);assertExactSigned(signed,template);const result=await publishVerifiedEvent(signed,relayConfig.writeRelays,1,authenticateWithBrowserExtension);setMessage(`Published to ${result.accepted.length} relay(s). The page is live.`);setEditor(null);await load(true);}catch(error){setMessage(error instanceof Error?error.message:"Content could not be published.");}finally{lock.current=false;setBusy(false);}}
 async function saveFlags(){if(lock.current)return;lock.current=true;setBusy(true);try{const actor=await getBrowserExtensionPubkey();if(!isSuperAdmin(actor)||actor!==dashboard.pubkey)throw new Error("Connect the BitcoinWalk super-admin identity.");const current=latestFeatureFlags(flagRows),template=createFeatureFlagsRevision({...flags,previousRevisionId:current?.event.id});setMessage("Review and sign this feature-flag change in your extension…");const signed=await signWithBrowserExtension(template);assertExactSigned(signed,template);const result=await publishVerifiedEvent(signed,relayConfig.writeRelays,1,authenticateWithBrowserExtension);setMessage(`Feature flags published to ${result.accepted.length} relay(s).`);await load(true);}catch(error){setMessage(error instanceof Error?error.message:"Feature flags could not be published.");}finally{lock.current=false;setBusy(false);}}
 return <main><p>BitcoinWalk / dashboard / content</p><h1>Content</h1><p>Edit the homepage, create static public pages and control staged functionality. Application routes, city URLs and walk-event URLs remain protected.</p><p role="status">{message}</p><section><h2>Feature flags</h2><label><input type="checkbox" checked={flags.paidTierRegistration} disabled={busy} onChange={event=>setFlags({...flags,paidTierRegistration:event.target.checked})}/> Enable Paid tier selection during walk registration</label><p>When disabled—or if the setting cannot be read—new registrations default to Free and the Paid choice is hidden.</p><button disabled={busy} onClick={saveFlags}>{busy?"Publishing…":"Sign and save feature flags"}</button></section><button disabled={busy||!!editor} onClick={()=>edit({page:{pageId:crypto.randomUUID(),slug:"new-page",title:"New page",eyebrow:"",intro:"",body:"",ctaLabel:"",ctaHref:"",footerTitle:"",footerText:"",footerCtaLabel:"",published:false}})}>+ Add page</button>
 {!editor?<section><h2>Pages</h2><ul>{listed.map(item=><li key={item.page.pageId}><strong>{item.page.pageId===HOME_PAGE_ID?"Homepage":item.page.title}</strong> — {item.page.slug?`/${item.page.slug}`:"/"} — {item.page.published?"Published":"Unpublished"} {item.page.published&&<a href={item.page.slug?`/${item.page.slug}`:"/"} target="_blank" rel="noreferrer">Open ↗</a>} <button disabled={busy} onClick={()=>edit(item)}>Edit</button></li>)}</ul></section>:<section><h2>Edit {editor.page.pageId===HOME_PAGE_ID?"Homepage":editor.page.title}</h2><label>URL<input value={editor.page.slug?`/${editor.page.slug}`:"/"} disabled={editor.page.pageId===HOME_PAGE_ID||busy} onChange={event=>field("slug",event.target.value.trim().replace(/^\/+|\/+$/g,"").toLowerCase())}/></label>{editor.page.pageId===HOME_PAGE_ID&&<p>The homepage URL is permanently `/`.</p>}<label>Eyebrow<input value={editor.page.eyebrow} disabled={busy} onChange={event=>field("eyebrow",event.target.value)}/></label><label>Page title<input required value={editor.page.title} disabled={busy} onChange={event=>field("title",event.target.value)}/></label><label>Introduction<textarea rows={4} value={editor.page.intro} disabled={busy} onChange={event=>field("intro",event.target.value)}/></label><label>Body<textarea rows={12} value={editor.page.body} disabled={busy} onChange={event=>field("body",event.target.value)}/></label><label>Call-to-action label<input value={editor.page.ctaLabel} disabled={busy} onChange={event=>field("ctaLabel",event.target.value)}/></label><label>Call-to-action URL<input value={editor.page.ctaHref} placeholder="/start or https://…" disabled={busy} onChange={event=>field("ctaHref",event.target.value)}/></label>{editor.page.pageId===HOME_PAGE_ID&&<><label>Footer title<input value={editor.page.footerTitle} disabled={busy} onChange={event=>field("footerTitle",event.target.value)}/></label><label>Footer text<textarea rows={3} value={editor.page.footerText} disabled={busy} onChange={event=>field("footerText",event.target.value)}/></label><label>Footer button label<input value={editor.page.footerCtaLabel} disabled={busy} onChange={event=>field("footerCtaLabel",event.target.value)}/></label></>}<label><input type="checkbox" checked={editor.page.published} disabled={busy||editor.page.pageId===HOME_PAGE_ID} onChange={event=>field("published",event.target.checked)}/> Published</label><p>Changing a published page URL keeps its previous URL as a redirect. Homepage changes keep the city directory and other live data.</p><button disabled={busy} onClick={save}>{busy?"Publishing…":"Sign and publish changes"}</button>{" "}<button disabled={busy} onClick={()=>{setEditor(null);setMessage("Changes discarded.");}}>Discard changes</button></section>}
 </main>;
}
