import {DatabaseSync} from "node:sqlite";
import {createHash} from "node:crypto";
import {beforeEach,afterEach,describe,expect,it,vi} from "vitest";
import {SponsorService} from "./sponsor-service";
const token="ab".repeat(32),other="cd".repeat(32),preimage="12".repeat(32),paymentHash=createHash("sha256").update(Buffer.from(preimage,"hex")).digest("hex"),cityId="00000000-0000-4000-8000-000000000001";
let db:DatabaseSync,now:number,service:SponsorService;
const wallet={makeSponsorInvoice:vi.fn(),lookupInvoice:vi.fn()},walks=Array.from({length:5},(_,i)=>({id:String(i+1).repeat(64),address:`walk-${i}`,start:2000100000+i*86400,label:`Walk ${i}`}));
beforeEach(()=>{vi.resetAllMocks();now=2000000000;db=new DatabaseSync(":memory:");wallet.makeSponsorInvoice.mockImplementation(async(_description,amount)=>({invoice:"lnbc-test",paymentHash,amountMsat:amount,createdAt:now,expiresAt:now+3600}));wallet.lookupInvoice.mockResolvedValue({payment_hash:paymentHash,type:"incoming",amount:21000000,state:"pending"});service=new SponsorService(db,wallet,async()=>[{id:cityId,name:"Warszawa",slug:"warszawa",walks}],()=>now);});
afterEach(()=>db.close());
describe("sponsorship checkout",()=>{
 it.each([[1,21000000],[2,42000000],[5,69000000]])("fixes package %i price on the server",async(count,amount)=>{const result=await service.create(token,"client",cityId,count,walks.slice(0,count).map(w=>w.id));expect(result.amountMsat).toBe(amount);expect(wallet.makeSponsorInvoice).toHaveBeenCalledWith(expect.any(String),amount);expect(result).not.toHaveProperty("tokenHash");expect(result).not.toHaveProperty("clientHash");});
 it("reuses one invoice across parallel retries and rejects competing bookings",async()=>{const [first,second]=await Promise.all([service.create(token,"client",cityId,1,[walks[0].id]),service.create(token,"client",cityId,1,[walks[0].id])]);expect(first.id).toBe(second.id);expect(wallet.makeSponsorInvoice).toHaveBeenCalledTimes(1);await expect(service.create(other,"other",cityId,1,[walks[0].id])).rejects.toThrow("no longer available");});
 it("rejects duplicate or insufficient selections before invoicing",async()=>{await expect(service.create(token,"client",cityId,2,[walks[0].id,walks[0].id])).rejects.toThrow();expect(wallet.makeSponsorInvoice).not.toHaveBeenCalled();});
 it("requires the recovery key and confirmed settlement before identity association",async()=>{const order=await service.create(token,"client",cityId,1,[walks[0].id]);await expect(service.status(order.id,other)).rejects.toThrow();await expect(service.claim(order.id,token,"aa".repeat(32),"signed")).rejects.toThrow("verified first");wallet.lookupInvoice.mockResolvedValue({payment_hash:paymentHash,type:"incoming",amount:21000000,state:"settled",settled_at:now,preimage});expect((await service.status(order.id,token)).status).toBe("paid");expect((await service.claim(order.id,token,"aa".repeat(32),"signed")).pubkey).toBe("aa".repeat(32));await expect(service.claim(order.id,token,"bb".repeat(32),"other")).rejects.toThrow("another identity");});
 it("does not accept a wrong amount or forged preimage",async()=>{const order=await service.create(token,"client",cityId,1,[walks[0].id]);wallet.lookupInvoice.mockResolvedValue({payment_hash:paymentHash,type:"incoming",amount:42000000,state:"settled",settled_at:now,preimage});await expect(service.status(order.id,token)).rejects.toThrow();wallet.lookupInvoice.mockResolvedValue({payment_hash:paymentHash,type:"incoming",amount:21000000,state:"settled",settled_at:now,preimage:"ff".repeat(32)});await expect(service.status(order.id,token)).rejects.toThrow();expect(service.list()[0].status).toBe("pending");});
 it("retains ambiguous creation and never issues a second invoice",async()=>{wallet.makeSponsorInvoice.mockRejectedValue(new Error("timeout"));const result=await service.create(token,"client",cityId,1,[walks[0].id]);expect(result.status).toBe("creation-uncertain");await service.create(token,"client",cityId,1,[walks[0].id]);expect(wallet.makeSponsorInvoice).toHaveBeenCalledTimes(1);});
 it("releases expired reservations and records late paid conflicts for review",async()=>{const order=await service.create(token,"client",cityId,1,[walks[0].id]);now+=3601;await service.status(order.id,token);expect((await service.available())[0].walks).toHaveLength(5);db.prepare("INSERT INTO sponsorship_reservation VALUES(?,?,?)").run(cityId,walks[0].address,"another-order");now+=11;wallet.lookupInvoice.mockResolvedValue({payment_hash:paymentHash,type:"incoming",amount:21000000,state:"settled",settled_at:now-20,preimage});const paid=await service.status(order.id,token);expect(paid.status).toBe("paid");expect(paid.needsReview).toBe(true);});
});
